# -*- coding: utf-8 -*-
from xlrd import open_workbook, xldate_as_tuple
from datetime import timedelta, date, datetime

from django.test import TestCase
from django.utils import timezone
from django.test import tag

from core.utils import export_to_excel_ws3, export_to_excel_ws

import locations.testing_utils as locaions_testing
import sows.testing_utils as sows_testings
import sows_events.utils as sows_events_testings
import staff.testing_utils as staff_testings

from sows.models import Sow
from sows_events.models import SowFarrow, CullingSow
from piglets.models import Piglets
from piglets_events.models import CullingPiglets, WeighingPiglets
from transactions.models import SowTransaction, PigletsTransaction
from locations.models import Location
from reports.models import ReportDate
from reports.serializers import ReportDateWs3Serializer


class ExportToExcelTest(TestCase):
    def setUp(self):
        locaions_testing.create_workshops_sections_and_cells()
        sows_testings.create_statuses()
        sows_events_testings.create_types()
        staff_testings.create_svinbin_users()

        self.data_ws3 = {
            "results": [
        {
            "id": 122,
            "count_sows_ws3_start_date": {
                "suporos": 53,
                "suporos2": 53,
                "podsos": 206,
                "podsos2": "206 , 0 , 0"
            },
            "created_at": "01-05-2020 17:38",
            "modified_at": "01-05-2020 17:38",
            "date": "2020-05-01",
            "padej_sup_count": None,
            "padej_sup_weight": None,
            "padej_podsos_count": None,
            "padej_podsos_weight": None,
            "vinuzhd_sup_count": None,
            "vinuzhd_sup_weight": None,
            "vinuzhd_podsos_count": None,
            "vinuzhd_podsos_weight": None,
            "tr_in_from_1_sup_count": None,
            "tr_in_from_2_sup_count": None,
            "tr_in_podsos_count": None,
            "tr_out_sup_count": None,
            "tr_out_podsos_count": 4,
            "count_oporos": None,
            "count_alive": None,
            "count_piglets_at_start": 471,
            "tr_out_aka_weight_qnty": None,
            "tr_out_aka_weight_total": None,
            "tr_out_aka_weight_avg": None,
            "piglets_padej_qnty": 8,
            "piglets_vinuzhd_qnty": None,
            "piglets_padej_weight": 0.0,
            "piglets_vinuzhd_weight": None
        },
        {
            "id": 123,
            "count_sows_ws3_start_date": {
                "suporos": 53,
                "suporos2": 53,
                "podsos": 202,
                "podsos2": "202 , 0 , 0"
            },
            "created_at": "01-05-2020 17:38",
            "modified_at": "01-05-2020 17:38",
            "date": "2020-05-02",
            "padej_sup_count": None,
            "padej_sup_weight": None,
            "padej_podsos_count": None,
            "padej_podsos_weight": None,
            "vinuzhd_sup_count": None,
            "vinuzhd_sup_weight": None,
            "vinuzhd_podsos_count": None,
            "vinuzhd_podsos_weight": None,
            "tr_in_from_1_sup_count": None,
            "tr_in_from_2_sup_count": 65,
            "tr_in_podsos_count": None,
            "tr_out_sup_count": None,
            "tr_out_podsos_count": None,
            "count_oporos": 23,
            "count_alive": 255,
            "count_piglets_at_start": 463,
            "tr_out_aka_weight_qnty": 637,
            "tr_out_aka_weight_total": 5235.0,
            "tr_out_aka_weight_avg": 8.27333333333333,
            "piglets_padej_qnty": 5,
            "piglets_vinuzhd_qnty": None,
            "piglets_padej_weight": 0.0,
            "piglets_vinuzhd_weight": None
        },
        {
            "id": 124,
            "count_sows_ws3_start_date": {
                "suporos": 96,
                "suporos2": 96,
                "podsos": 225,
                "podsos2": "177 , 48 , 0"
            },
            "created_at": "01-05-2020 17:38",
            "modified_at": "01-05-2020 17:38",
            "date": "2020-05-03",
            "padej_sup_count": None,
            "padej_sup_weight": None,
            "padej_podsos_count": None,
            "padej_podsos_weight": None,
            "vinuzhd_sup_count": None,
            "vinuzhd_sup_weight": None,
            "vinuzhd_podsos_count": None,
            "vinuzhd_podsos_weight": None,
            "tr_in_from_1_sup_count": None,
            "tr_in_from_2_sup_count": None,
            "tr_in_podsos_count": None,
            "tr_out_sup_count": None,
            "tr_out_podsos_count": 47,
            "count_oporos": 5,
            "count_alive": 44,
            "count_piglets_at_start": 76,
            "tr_out_aka_weight_qnty": None,
            "tr_out_aka_weight_total": None,
            "tr_out_aka_weight_avg": None,
            "piglets_padej_qnty": 6,
            "piglets_vinuzhd_qnty": None,
            "piglets_padej_weight": 0.0,
            "piglets_vinuzhd_weight": None
        },
        {
            "id": 125,
            "count_sows_ws3_start_date": {
                "suporos": 91,
                "suporos2": 91,
                "podsos": 185,
                "podsos2": "181 , 4 , 0"
            },
            "created_at": "01-05-2020 17:38",
            "modified_at": "01-05-2020 17:38",
            "date": "2020-05-04",
            "padej_sup_count": 3,
            "padej_sup_weight": None,
            "padej_podsos_count": None,
            "padej_podsos_weight": None,
            "vinuzhd_sup_count": None,
            "vinuzhd_sup_weight": None,
            "vinuzhd_podsos_count": None,
            "vinuzhd_podsos_weight": None,
            "tr_in_from_1_sup_count": None,
            "tr_in_from_2_sup_count": None,
            "tr_in_podsos_count": None,
            "tr_out_sup_count": None,
            "tr_out_podsos_count": 3,
            "count_oporos": 9,
            "count_alive": 88,
            "count_piglets_at_start": 114,
            "tr_out_aka_weight_qnty": None,
            "tr_out_aka_weight_total": None,
            "tr_out_aka_weight_avg": None,
            "piglets_padej_qnty": 7,
            "piglets_vinuzhd_qnty": None,
            "piglets_padej_weight": 0.0,
            "piglets_vinuzhd_weight": None
        },
        {
            "id": 126,
            "count_sows_ws3_start_date": {
                "suporos": 78,
                "suporos2": 78,
                "podsos": 192,
                "podsos2": "188 , 4 , 0"
            },
            "created_at": "01-05-2020 17:38",
            "modified_at": "01-05-2020 17:38",
            "date": "2020-05-05",
            "padej_sup_count": None,
            "padej_sup_weight": None,
            "padej_podsos_count": None,
            "padej_podsos_weight": None,
            "vinuzhd_sup_count": None,
            "vinuzhd_sup_weight": None,
            "vinuzhd_podsos_count": None,
            "vinuzhd_podsos_weight": None,
            "tr_in_from_1_sup_count": None,
            "tr_in_from_2_sup_count": None,
            "tr_in_podsos_count": None,
            "tr_out_sup_count": None,
            "tr_out_podsos_count": None,
            "count_oporos": 6,
            "count_alive": 51,
            "count_piglets_at_start": 195,
            "tr_out_aka_weight_qnty": None,
            "tr_out_aka_weight_total": None,
            "tr_out_aka_weight_avg": None,
            "piglets_padej_qnty": 7,
            "piglets_vinuzhd_qnty": None,
            "piglets_padej_weight": 0.0,
            "piglets_vinuzhd_weight": None
        },
        {
            "id": 127,
            "count_sows_ws3_start_date": {
                "suporos": 72,
                "suporos2": 72,
                "podsos": 198,
                "podsos2": "194 , 4 , 0"
            },
            "created_at": "01-05-2020 17:38",
            "modified_at": "01-05-2020 17:38",
            "date": "2020-05-06",
            "padej_sup_count": None,
            "padej_sup_weight": None,
            "padej_podsos_count": None,
            "padej_podsos_weight": None,
            "vinuzhd_sup_count": None,
            "vinuzhd_sup_weight": None,
            "vinuzhd_podsos_count": None,
            "vinuzhd_podsos_weight": None,
            "tr_in_from_1_sup_count": None,
            "tr_in_from_2_sup_count": 1,
            "tr_in_podsos_count": None,
            "tr_out_sup_count": None,
            "tr_out_podsos_count": 6,
            "count_oporos": 9,
            "count_alive": 112,
            "count_piglets_at_start": 239,
            "tr_out_aka_weight_qnty": 617,
            "tr_out_aka_weight_total": 4649.0,
            "tr_out_aka_weight_avg": 7.57833333333333,
            "piglets_padej_qnty": 12,
            "piglets_vinuzhd_qnty": None,
            "piglets_padej_weight": 0.0,
            "piglets_vinuzhd_weight": None
        },
        {
            "id": 128,
            "count_sows_ws3_start_date": {
                "suporos": 59,
                "suporos2": 59,
                "podsos": 206,
                "podsos2": "202 , 4 , 0"
            },
            "created_at": "01-05-2020 17:38",
            "modified_at": "01-05-2020 17:38",
            "date": "2020-05-07",
            "padej_sup_count": None,
            "padej_sup_weight": None,
            "padej_podsos_count": 2,
            "padej_podsos_weight": None,
            "vinuzhd_sup_count": None,
            "vinuzhd_sup_weight": None,
            "vinuzhd_podsos_count": None,
            "vinuzhd_podsos_weight": None,
            "tr_in_from_1_sup_count": None,
            "tr_in_from_2_sup_count": None,
            "tr_in_podsos_count": None,
            "tr_out_sup_count": None,
            "tr_out_podsos_count": None,
            "count_oporos": 1,
            "count_alive": 7,
            "count_piglets_at_start": -278,
            "tr_out_aka_weight_qnty": None,
            "tr_out_aka_weight_total": None,
            "tr_out_aka_weight_avg": None,
            "piglets_padej_qnty": 12,
            "piglets_vinuzhd_qnty": None,
            "piglets_padej_weight": 0.0,
            "piglets_vinuzhd_weight": None
        },
        {
            "id": 129,
            "count_sows_ws3_start_date": {
                "suporos": 58,
                "suporos2": 58,
                "podsos": 205,
                "podsos2": "201 , 4 , 0"
            },
            "created_at": "01-05-2020 17:38",
            "modified_at": "01-05-2020 17:38",
            "date": "2020-05-08",
            "padej_sup_count": None,
            "padej_sup_weight": None,
            "padej_podsos_count": None,
            "padej_podsos_weight": None,
            "vinuzhd_sup_count": None,
            "vinuzhd_sup_weight": None,
            "vinuzhd_podsos_count": None,
            "vinuzhd_podsos_weight": None,
            "tr_in_from_1_sup_count": None,
            "tr_in_from_2_sup_count": None,
            "tr_in_podsos_count": None,
            "tr_out_sup_count": None,
            "tr_out_podsos_count": 5,
            "count_oporos": 8,
            "count_alive": 94,
            "count_piglets_at_start": -283,
            "tr_out_aka_weight_qnty": None,
            "tr_out_aka_weight_total": None,
            "tr_out_aka_weight_avg": None,
            "piglets_padej_qnty": 10,
            "piglets_vinuzhd_qnty": None,
            "piglets_padej_weight": 0.0,
            "piglets_vinuzhd_weight": None
        },
        {
            "id": 130,
            "count_sows_ws3_start_date": {
                "suporos": 50,
                "suporos2": 50,
                "podsos": 208,
                "podsos2": "204 , 4 , 0"
            },
            "created_at": "01-05-2020 17:38",
            "modified_at": "01-05-2020 17:38",
            "date": "2020-05-09",
            "padej_sup_count": 1,
            "padej_sup_weight": None,
            "padej_podsos_count": 1,
            "padej_podsos_weight": None,
            "vinuzhd_sup_count": None,
            "vinuzhd_sup_weight": None,
            "vinuzhd_podsos_count": None,
            "vinuzhd_podsos_weight": None,
            "tr_in_from_1_sup_count": None,
            "tr_in_from_2_sup_count": 62,
            "tr_in_podsos_count": 1,
            "tr_out_sup_count": None,
            "tr_out_podsos_count": 54,
            "count_oporos": 41,
            "count_alive": 452,
            "count_piglets_at_start": -199,
            "tr_out_aka_weight_qnty": None,
            "tr_out_aka_weight_total": None,
            "tr_out_aka_weight_avg": None,
            "piglets_padej_qnty": 19,
            "piglets_vinuzhd_qnty": None,
            "piglets_padej_weight": 0.0,
            "piglets_vinuzhd_weight": None
        },
        {
            "id": 131,
            "count_sows_ws3_start_date": {
                "suporos": 71,
                "suporos2": 71,
                "podsos": 194,
                "podsos2": "187 , 7 , 0"
            },
            "created_at": "01-05-2020 17:38",
            "modified_at": "01-05-2020 17:38",
            "date": "2020-05-10",
            "padej_sup_count": 1,
            "padej_sup_weight": None,
            "padej_podsos_count": None,
            "padej_podsos_weight": None,
            "vinuzhd_sup_count": None,
            "vinuzhd_sup_weight": None,
            "vinuzhd_podsos_count": None,
            "vinuzhd_podsos_weight": None,
            "tr_in_from_1_sup_count": None,
            "tr_in_from_2_sup_count": None,
            "tr_in_podsos_count": None,
            "tr_out_sup_count": None,
            "tr_out_podsos_count": None,
            "count_oporos": None,
            "count_alive": None,
            "count_piglets_at_start": 234,
            "tr_out_aka_weight_qnty": None,
            "tr_out_aka_weight_total": None,
            "tr_out_aka_weight_avg": None,
            "piglets_padej_qnty": 5,
            "piglets_vinuzhd_qnty": None,
            "piglets_padej_weight": 0.0,
            "piglets_vinuzhd_weight": None
        },
        {
            "id": 132,
            "count_sows_ws3_start_date": {
                "suporos": 70,
                "suporos2": 70,
                "podsos": 194,
                "podsos2": "187 , 7 , 0"
            },
            "created_at": "01-05-2020 17:38",
            "modified_at": "01-05-2020 17:38",
            "date": "2020-05-11",
            "padej_sup_count": 1,
            "padej_sup_weight": None,
            "padej_podsos_count": None,
            "padej_podsos_weight": None,
            "vinuzhd_sup_count": None,
            "vinuzhd_sup_weight": None,
            "vinuzhd_podsos_count": None,
            "vinuzhd_podsos_weight": None,
            "tr_in_from_1_sup_count": None,
            "tr_in_from_2_sup_count": None,
            "tr_in_podsos_count": None,
            "tr_out_sup_count": None,
            "tr_out_podsos_count": None,
            "count_oporos": 9,
            "count_alive": 101,
            "count_piglets_at_start": 229,
            "tr_out_aka_weight_qnty": None,
            "tr_out_aka_weight_total": None,
            "tr_out_aka_weight_avg": None,
            "piglets_padej_qnty": 15,
            "piglets_vinuzhd_qnty": None,
            "piglets_padej_weight": 0.0,
            "piglets_vinuzhd_weight": None
        },
        {
            "id": 133,
            "count_sows_ws3_start_date": {
                "suporos": 60,
                "suporos2": 60,
                "podsos": 203,
                "podsos2": "196 , 7 , 0"
            },
            "created_at": "01-05-2020 17:38",
            "modified_at": "01-05-2020 17:38",
            "date": "2020-05-12",
            "padej_sup_count": None,
            "padej_sup_weight": None,
            "padej_podsos_count": None,
            "padej_podsos_weight": None,
            "vinuzhd_sup_count": None,
            "vinuzhd_sup_weight": None,
            "vinuzhd_podsos_count": None,
            "vinuzhd_podsos_weight": None,
            "tr_in_from_1_sup_count": None,
            "tr_in_from_2_sup_count": None,
            "tr_in_podsos_count": None,
            "tr_out_sup_count": None,
            "tr_out_podsos_count": None,
            "count_oporos": 5,
            "count_alive": 64,
            "count_piglets_at_start": 315,
            "tr_out_aka_weight_qnty": None,
            "tr_out_aka_weight_total": None,
            "tr_out_aka_weight_avg": None,
            "piglets_padej_qnty": 10,
            "piglets_vinuzhd_qnty": None,
            "piglets_padej_weight": 0.0,
            "piglets_vinuzhd_weight": None
        },
        {
            "id": 134,
            "count_sows_ws3_start_date": {
                "suporos": 55,
                "suporos2": 55,
                "podsos": 208,
                "podsos2": "201 , 7 , 0"
            },
            "created_at": "01-05-2020 17:38",
            "modified_at": "01-05-2020 17:38",
            "date": "2020-05-13",
            "padej_sup_count": None,
            "padej_sup_weight": None,
            "padej_podsos_count": None,
            "padej_podsos_weight": None,
            "vinuzhd_sup_count": None,
            "vinuzhd_sup_weight": None,
            "vinuzhd_podsos_count": None,
            "vinuzhd_podsos_weight": None,
            "tr_in_from_1_sup_count": None,
            "tr_in_from_2_sup_count": None,
            "tr_in_podsos_count": None,
            "tr_out_sup_count": None,
            "tr_out_podsos_count": None,
            "count_oporos": 10,
            "count_alive": 116,
            "count_piglets_at_start": 369,
            "tr_out_aka_weight_qnty": None,
            "tr_out_aka_weight_total": None,
            "tr_out_aka_weight_avg": None,
            "piglets_padej_qnty": 12,
            "piglets_vinuzhd_qnty": None,
            "piglets_padej_weight": 0.0,
            "piglets_vinuzhd_weight": None
        },
        {
            "id": 135,
            "count_sows_ws3_start_date": {
                "suporos": 45,
                "suporos2": 45,
                "podsos": 218,
                "podsos2": "211 , 7 , 0"
            },
            "created_at": "01-05-2020 17:38",
            "modified_at": "01-05-2020 17:38",
            "date": "2020-05-14",
            "padej_sup_count": None,
            "padej_sup_weight": None,
            "padej_podsos_count": None,
            "padej_podsos_weight": None,
            "vinuzhd_sup_count": None,
            "vinuzhd_sup_weight": None,
            "vinuzhd_podsos_count": None,
            "vinuzhd_podsos_weight": None,
            "tr_in_from_1_sup_count": None,
            "tr_in_from_2_sup_count": None,
            "tr_in_podsos_count": None,
            "tr_out_sup_count": None,
            "tr_out_podsos_count": None,
            "count_oporos": None,
            "count_alive": None,
            "count_piglets_at_start": 473,
            "tr_out_aka_weight_qnty": None,
            "tr_out_aka_weight_total": None,
            "tr_out_aka_weight_avg": None,
            "piglets_padej_qnty": 10,
            "piglets_vinuzhd_qnty": None,
            "piglets_padej_weight": 0.0,
            "piglets_vinuzhd_weight": None
        },
        {
            "id": 136,
            "count_sows_ws3_start_date": {
                "suporos": 46,
                "suporos2": 46,
                "podsos": 218,
                "podsos2": "211 , 7 , 0"
            },
            "created_at": "01-05-2020 17:38",
            "modified_at": "01-05-2020 17:38",
            "date": "2020-05-15",
            "padej_sup_count": 1,
            "padej_sup_weight": None,
            "padej_podsos_count": 2,
            "padej_podsos_weight": None,
            "vinuzhd_sup_count": None,
            "vinuzhd_sup_weight": None,
            "vinuzhd_podsos_count": None,
            "vinuzhd_podsos_weight": None,
            "tr_in_from_1_sup_count": None,
            "tr_in_from_2_sup_count": None,
            "tr_in_podsos_count": None,
            "tr_out_sup_count": None,
            "tr_out_podsos_count": 2,
            "count_oporos": 21,
            "count_alive": 251,
            "count_piglets_at_start": 463,
            "tr_out_aka_weight_qnty": 590,
            "tr_out_aka_weight_total": 4506.0,
            "tr_out_aka_weight_avg": 7.636,
            "piglets_padej_qnty": 11,
            "piglets_vinuzhd_qnty": None,
            "piglets_padej_weight": 0.0,
            "piglets_vinuzhd_weight": None
        },
        {
            "id": 137,
            "count_sows_ws3_start_date": {
                "suporos": 24,
                "suporos2": 24,
                "podsos": 235,
                "podsos2": "228 , 6 , 1"
            },
            "created_at": "01-05-2020 17:38",
            "modified_at": "01-05-2020 17:38",
            "date": "2020-05-16",
            "padej_sup_count": None,
            "padej_sup_weight": None,
            "padej_podsos_count": 1,
            "padej_podsos_weight": None,
            "vinuzhd_sup_count": None,
            "vinuzhd_sup_weight": None,
            "vinuzhd_podsos_count": None,
            "vinuzhd_podsos_weight": None,
            "tr_in_from_1_sup_count": None,
            "tr_in_from_2_sup_count": None,
            "tr_in_podsos_count": None,
            "tr_out_sup_count": None,
            "tr_out_podsos_count": 49,
            "count_oporos": 4,
            "count_alive": 49,
            "count_piglets_at_start": 113,
            "tr_out_aka_weight_qnty": None,
            "tr_out_aka_weight_total": None,
            "tr_out_aka_weight_avg": None,
            "piglets_padej_qnty": 10,
            "piglets_vinuzhd_qnty": None,
            "piglets_padej_weight": 0.0,
            "piglets_vinuzhd_weight": None
        },
        {
            "id": 138,
            "count_sows_ws3_start_date": {
                "suporos": 20,
                "suporos2": 20,
                "podsos": 190,
                "podsos2": "187 , 2 , 1"
            },
            "created_at": "01-05-2020 17:38",
            "modified_at": "01-05-2020 17:38",
            "date": "2020-05-17",
            "padej_sup_count": None,
            "padej_sup_weight": None,
            "padej_podsos_count": None,
            "padej_podsos_weight": None,
            "vinuzhd_sup_count": None,
            "vinuzhd_sup_weight": None,
            "vinuzhd_podsos_count": None,
            "vinuzhd_podsos_weight": None,
            "tr_in_from_1_sup_count": None,
            "tr_in_from_2_sup_count": None,
            "tr_in_podsos_count": None,
            "tr_out_sup_count": None,
            "tr_out_podsos_count": None,
            "count_oporos": 3,
            "count_alive": 32,
            "count_piglets_at_start": 152,
            "tr_out_aka_weight_qnty": None,
            "tr_out_aka_weight_total": None,
            "tr_out_aka_weight_avg": None,
            "piglets_padej_qnty": 6,
            "piglets_vinuzhd_qnty": None,
            "piglets_padej_weight": 0.0,
            "piglets_vinuzhd_weight": None
        },
        {
            "id": 139,
            "count_sows_ws3_start_date": {
                "suporos": 17,
                "suporos2": 17,
                "podsos": 193,
                "podsos2": "190 , 2 , 1"
            },
            "created_at": "01-05-2020 17:38",
            "modified_at": "01-05-2020 17:38",
            "date": "2020-05-18",
            "padej_sup_count": 1,
            "padej_sup_weight": None,
            "padej_podsos_count": 2,
            "padej_podsos_weight": None,
            "vinuzhd_sup_count": None,
            "vinuzhd_sup_weight": None,
            "vinuzhd_podsos_count": None,
            "vinuzhd_podsos_weight": None,
            "tr_in_from_1_sup_count": None,
            "tr_in_from_2_sup_count": 59,
            "tr_in_podsos_count": None,
            "tr_out_sup_count": None,
            "tr_out_podsos_count": None,
            "count_oporos": 1,
            "count_alive": 13,
            "count_piglets_at_start": 178,
            "tr_out_aka_weight_qnty": None,
            "tr_out_aka_weight_total": None,
            "tr_out_aka_weight_avg": None,
            "piglets_padej_qnty": 8,
            "piglets_vinuzhd_qnty": None,
            "piglets_padej_weight": 0.0,
            "piglets_vinuzhd_weight": None
        },
        {
            "id": 140,
            "count_sows_ws3_start_date": {
                "suporos": 74,
                "suporos2": 74,
                "podsos": 192,
                "podsos2": "189 , 2 , 1"
            },
            "created_at": "01-05-2020 17:38",
            "modified_at": "01-05-2020 17:38",
            "date": "2020-05-19",
            "padej_sup_count": 1,
            "padej_sup_weight": None,
            "padej_podsos_count": None,
            "padej_podsos_weight": None,
            "vinuzhd_sup_count": None,
            "vinuzhd_sup_weight": None,
            "vinuzhd_podsos_count": None,
            "vinuzhd_podsos_weight": None,
            "tr_in_from_1_sup_count": None,
            "tr_in_from_2_sup_count": None,
            "tr_in_podsos_count": None,
            "tr_out_sup_count": None,
            "tr_out_podsos_count": None,
            "count_oporos": 14,
            "count_alive": 173,
            "count_piglets_at_start": 183,
            "tr_out_aka_weight_qnty": None,
            "tr_out_aka_weight_total": None,
            "tr_out_aka_weight_avg": None,
            "piglets_padej_qnty": 7,
            "piglets_vinuzhd_qnty": None,
            "piglets_padej_weight": 0.0,
            "piglets_vinuzhd_weight": None
        },
        {
            "id": 141,
            "count_sows_ws3_start_date": {
                "suporos": 59,
                "suporos2": 59,
                "podsos": 206,
                "podsos2": "203 , 2 , 1"
            },
            "created_at": "01-05-2020 17:38",
            "modified_at": "01-05-2020 17:38",
            "date": "2020-05-20",
            "padej_sup_count": None,
            "padej_sup_weight": None,
            "padej_podsos_count": None,
            "padej_podsos_weight": None,
            "vinuzhd_sup_count": None,
            "vinuzhd_sup_weight": None,
            "vinuzhd_podsos_count": None,
            "vinuzhd_podsos_weight": None,
            "tr_in_from_1_sup_count": None,
            "tr_in_from_2_sup_count": 1,
            "tr_in_podsos_count": None,
            "tr_out_sup_count": None,
            "tr_out_podsos_count": None,
            "count_oporos": 16,
            "count_alive": 178,
            "count_piglets_at_start": 349,
            "tr_out_aka_weight_qnty": None,
            "tr_out_aka_weight_total": None,
            "tr_out_aka_weight_avg": None,
            "piglets_padej_qnty": 11,
            "piglets_vinuzhd_qnty": None,
            "piglets_padej_weight": 0.0,
            "piglets_vinuzhd_weight": None
        },
        {
            "id": 142,
            "count_sows_ws3_start_date": {
                "suporos": 44,
                "suporos2": 44,
                "podsos": 222,
                "podsos2": "218 , 2 , 2"
            },
            "created_at": "01-05-2020 17:38",
            "modified_at": "01-05-2020 17:38",
            "date": "2020-05-21",
            "padej_sup_count": 2,
            "padej_sup_weight": None,
            "padej_podsos_count": 1,
            "padej_podsos_weight": None,
            "vinuzhd_sup_count": None,
            "vinuzhd_sup_weight": None,
            "vinuzhd_podsos_count": None,
            "vinuzhd_podsos_weight": None,
            "tr_in_from_1_sup_count": None,
            "tr_in_from_2_sup_count": None,
            "tr_in_podsos_count": None,
            "tr_out_sup_count": None,
            "tr_out_podsos_count": None,
            "count_oporos": 9,
            "count_alive": 112,
            "count_piglets_at_start": 516,
            "tr_out_aka_weight_qnty": None,
            "tr_out_aka_weight_total": None,
            "tr_out_aka_weight_avg": None,
            "piglets_padej_qnty": 13,
            "piglets_vinuzhd_qnty": None,
            "piglets_padej_weight": 0.0,
            "piglets_vinuzhd_weight": None
        },
        {
            "id": 143,
            "count_sows_ws3_start_date": {
                "suporos": 33,
                "suporos2": 33,
                "podsos": 230,
                "podsos2": "225 , 2 , 3"
            },
            "created_at": "01-05-2020 17:38",
            "modified_at": "01-05-2020 17:38",
            "date": "2020-05-22",
            "padej_sup_count": 1,
            "padej_sup_weight": None,
            "padej_podsos_count": None,
            "padej_podsos_weight": None,
            "vinuzhd_sup_count": None,
            "vinuzhd_sup_weight": None,
            "vinuzhd_podsos_count": None,
            "vinuzhd_podsos_weight": None,
            "tr_in_from_1_sup_count": None,
            "tr_in_from_2_sup_count": None,
            "tr_in_podsos_count": None,
            "tr_out_sup_count": None,
            "tr_out_podsos_count": None,
            "count_oporos": 22,
            "count_alive": 251,
            "count_piglets_at_start": 615,
            "tr_out_aka_weight_qnty": 548,
            "tr_out_aka_weight_total": 4337.0,
            "tr_out_aka_weight_avg": 7.856,
            "piglets_padej_qnty": 9,
            "piglets_vinuzhd_qnty": None,
            "piglets_padej_weight": 0.0,
            "piglets_vinuzhd_weight": None
        },
        {
            "id": 144,
            "count_sows_ws3_start_date": {
                "suporos": 10,
                "suporos2": 10,
                "podsos": 252,
                "podsos2": "246 , 2 , 4"
            },
            "created_at": "01-05-2020 17:38",
            "modified_at": "01-05-2020 17:38",
            "date": "2020-05-23",
            "padej_sup_count": None,
            "padej_sup_weight": None,
            "padej_podsos_count": 1,
            "padej_podsos_weight": None,
            "vinuzhd_sup_count": None,
            "vinuzhd_sup_weight": None,
            "vinuzhd_podsos_count": None,
            "vinuzhd_podsos_weight": None,
            "tr_in_from_1_sup_count": None,
            "tr_in_from_2_sup_count": None,
            "tr_in_podsos_count": None,
            "tr_out_sup_count": None,
            "tr_out_podsos_count": 52,
            "count_oporos": 6,
            "count_alive": 48,
            "count_piglets_at_start": 309,
            "tr_out_aka_weight_qnty": None,
            "tr_out_aka_weight_total": None,
            "tr_out_aka_weight_avg": None,
            "piglets_padej_qnty": 14,
            "piglets_vinuzhd_qnty": None,
            "piglets_padej_weight": 0.0,
            "piglets_vinuzhd_weight": None
        },
        {
            "id": 145,
            "count_sows_ws3_start_date": {
                "suporos": 4,
                "suporos2": 4,
                "podsos": 205,
                "podsos2": "199 , 2 , 4"
            },
            "created_at": "01-05-2020 17:38",
            "modified_at": "01-05-2020 17:38",
            "date": "2020-05-24",
            "padej_sup_count": None,
            "padej_sup_weight": None,
            "padej_podsos_count": None,
            "padej_podsos_weight": None,
            "vinuzhd_sup_count": None,
            "vinuzhd_sup_weight": None,
            "vinuzhd_podsos_count": None,
            "vinuzhd_podsos_weight": None,
            "tr_in_from_1_sup_count": None,
            "tr_in_from_2_sup_count": None,
            "tr_in_podsos_count": None,
            "tr_out_sup_count": None,
            "tr_out_podsos_count": None,
            "count_oporos": 1,
            "count_alive": 5,
            "count_piglets_at_start": 343,
            "tr_out_aka_weight_qnty": None,
            "tr_out_aka_weight_total": None,
            "tr_out_aka_weight_avg": None,
            "piglets_padej_qnty": 8,
            "piglets_vinuzhd_qnty": None,
            "piglets_padej_weight": 0.0,
            "piglets_vinuzhd_weight": None
        },
        {
            "id": 146,
            "count_sows_ws3_start_date": {
                "suporos": 3,
                "suporos2": 3,
                "podsos": 206,
                "podsos2": "200 , 2 , 4"
            },
            "created_at": "01-05-2020 17:38",
            "modified_at": "01-05-2020 17:38",
            "date": "2020-05-25",
            "padej_sup_count": None,
            "padej_sup_weight": None,
            "padej_podsos_count": None,
            "padej_podsos_weight": None,
            "vinuzhd_sup_count": None,
            "vinuzhd_sup_weight": None,
            "vinuzhd_podsos_count": None,
            "vinuzhd_podsos_weight": None,
            "tr_in_from_1_sup_count": None,
            "tr_in_from_2_sup_count": 61,
            "tr_in_podsos_count": None,
            "tr_out_sup_count": None,
            "tr_out_podsos_count": None,
            "count_oporos": 2,
            "count_alive": 21,
            "count_piglets_at_start": 340,
            "tr_out_aka_weight_qnty": None,
            "tr_out_aka_weight_total": None,
            "tr_out_aka_weight_avg": None,
            "piglets_padej_qnty": 13,
            "piglets_vinuzhd_qnty": None,
            "piglets_padej_weight": 0.0,
            "piglets_vinuzhd_weight": None
        },
        {
            "id": 147,
            "count_sows_ws3_start_date": {
                "suporos": 63,
                "suporos2": 63,
                "podsos": 207,
                "podsos2": "201 , 2 , 4"
            },
            "created_at": "01-05-2020 17:38",
            "modified_at": "01-05-2020 17:38",
            "date": "2020-05-26",
            "padej_sup_count": None,
            "padej_sup_weight": None,
            "padej_podsos_count": None,
            "padej_podsos_weight": None,
            "vinuzhd_sup_count": None,
            "vinuzhd_sup_weight": None,
            "vinuzhd_podsos_count": None,
            "vinuzhd_podsos_weight": None,
            "tr_in_from_1_sup_count": None,
            "tr_in_from_2_sup_count": None,
            "tr_in_podsos_count": None,
            "tr_out_sup_count": None,
            "tr_out_podsos_count": None,
            "count_oporos": None,
            "count_alive": None,
            "count_piglets_at_start": 348,
            "tr_out_aka_weight_qnty": None,
            "tr_out_aka_weight_total": None,
            "tr_out_aka_weight_avg": None,
            "piglets_padej_qnty": 13,
            "piglets_vinuzhd_qnty": None,
            "piglets_padej_weight": 0.0,
            "piglets_vinuzhd_weight": None
        },
        {
            "id": 148,
            "count_sows_ws3_start_date": {
                "suporos": 63,
                "suporos2": 63,
                "podsos": 207,
                "podsos2": "201 , 2 , 4"
            },
            "created_at": "01-05-2020 17:38",
            "modified_at": "01-05-2020 17:38",
            "date": "2020-05-27",
            "padej_sup_count": None,
            "padej_sup_weight": None,
            "padej_podsos_count": None,
            "padej_podsos_weight": None,
            "vinuzhd_sup_count": None,
            "vinuzhd_sup_weight": None,
            "vinuzhd_podsos_count": None,
            "vinuzhd_podsos_weight": None,
            "tr_in_from_1_sup_count": None,
            "tr_in_from_2_sup_count": None,
            "tr_in_podsos_count": None,
            "tr_out_sup_count": None,
            "tr_out_podsos_count": None,
            "count_oporos": 5,
            "count_alive": 56,
            "count_piglets_at_start": 335,
            "tr_out_aka_weight_qnty": None,
            "tr_out_aka_weight_total": None,
            "tr_out_aka_weight_avg": None,
            "piglets_padej_qnty": 8,
            "piglets_vinuzhd_qnty": None,
            "piglets_padej_weight": 0.0,
            "piglets_vinuzhd_weight": None
        },
        {
            "id": 149,
            "count_sows_ws3_start_date": {
                "suporos": 59,
                "suporos2": 59,
                "podsos": 212,
                "podsos2": "205 , 2 , 5"
            },
            "created_at": "01-05-2020 17:38",
            "modified_at": "01-05-2020 17:38",
            "date": "2020-05-28",
            "padej_sup_count": None,
            "padej_sup_weight": None,
            "padej_podsos_count": None,
            "padej_podsos_weight": None,
            "vinuzhd_sup_count": None,
            "vinuzhd_sup_weight": None,
            "vinuzhd_podsos_count": None,
            "vinuzhd_podsos_weight": None,
            "tr_in_from_1_sup_count": None,
            "tr_in_from_2_sup_count": None,
            "tr_in_podsos_count": None,
            "tr_out_sup_count": None,
            "tr_out_podsos_count": None,
            "count_oporos": None,
            "count_alive": None,
            "count_piglets_at_start": 383,
            "tr_out_aka_weight_qnty": None,
            "tr_out_aka_weight_total": None,
            "tr_out_aka_weight_avg": None,
            "piglets_padej_qnty": 5,
            "piglets_vinuzhd_qnty": None,
            "piglets_padej_weight": 0.0,
            "piglets_vinuzhd_weight": None
        },
        {
            "id": 150,
            "count_sows_ws3_start_date": {
                "suporos": 59,
                "suporos2": 59,
                "podsos": 212,
                "podsos2": "205 , 2 , 5"
            },
            "created_at": "01-05-2020 17:38",
            "modified_at": "01-05-2020 17:38",
            "date": "2020-05-29",
            "padej_sup_count": None,
            "padej_sup_weight": None,
            "padej_podsos_count": None,
            "padej_podsos_weight": None,
            "vinuzhd_sup_count": None,
            "vinuzhd_sup_weight": None,
            "vinuzhd_podsos_count": None,
            "vinuzhd_podsos_weight": None,
            "tr_in_from_1_sup_count": None,
            "tr_in_from_2_sup_count": None,
            "tr_in_podsos_count": None,
            "tr_out_sup_count": None,
            "tr_out_podsos_count": None,
            "count_oporos": None,
            "count_alive": None,
            "count_piglets_at_start": 378,
            "tr_out_aka_weight_qnty": None,
            "tr_out_aka_weight_total": None,
            "tr_out_aka_weight_avg": None,
            "piglets_padej_qnty": None,
            "piglets_vinuzhd_qnty": None,
            "piglets_padej_weight": None,
            "piglets_vinuzhd_weight": None
        },
        {
            "id": 151,
            "count_sows_ws3_start_date": {
                "suporos": 59,
                "suporos2": 59,
                "podsos": 212,
                "podsos2": "205 , 2 , 5"
            },
            "created_at": "01-05-2020 17:38",
            "modified_at": "01-05-2020 17:38",
            "date": "2020-05-30",
            "padej_sup_count": None,
            "padej_sup_weight": None,
            "padej_podsos_count": None,
            "padej_podsos_weight": None,
            "vinuzhd_sup_count": None,
            "vinuzhd_sup_weight": None,
            "vinuzhd_podsos_count": None,
            "vinuzhd_podsos_weight": None,
            "tr_in_from_1_sup_count": None,
            "tr_in_from_2_sup_count": None,
            "tr_in_podsos_count": None,
            "tr_out_sup_count": None,
            "tr_out_podsos_count": None,
            "count_oporos": None,
            "count_alive": None,
            "count_piglets_at_start": 378,
            "tr_out_aka_weight_qnty": None,
            "tr_out_aka_weight_total": None,
            "tr_out_aka_weight_avg": None,
            "piglets_padej_qnty": None,
            "piglets_vinuzhd_qnty": None,
            "piglets_padej_weight": None,
            "piglets_vinuzhd_weight": None
        }
        ],
        "total_info": {
            "total_tr_in_podsos_count": 1,
            "total_tr_in_from_1_sup_count": None,
            "total_tr_in_from_2_sup_count": 249,
            "total_count_oporos": 230,
            "total_count_alive": 2573,
            "total_tr_out_podsos_count": 222,
            "total_tr_out_sup_count": None,
            "total_padej_podsos_count": 10,
            "total_padej_podsos_weight": None,
            "total_padej_sup_count": 12,
            "total_padej_sup_weight": None,
            "total_vinuzhd_podsos_count": None,
            "total_vinuzhd_podsos_weight": None,
            "total_vinuzhd_sup_count": None,
            "total_vinuzhd_sup_weight": None,
            "total_tr_out_aka_weight_qnty": 2392,
            "total_tr_out_aka_weight_total": 18727.0,
            "avg_tr_out_weight": 7.83591666666667,
            "total_piglets_padej_qnty": 274,
            "total_piglets_padej_weight": 0.0,
            "total_piglets_vinuzhd_qnty": None,
            "total_piglets_vinuzhd_weight": None
            }
        }

        self.data_ws = {
            "results": [
                {
                    "id": 165,
                    "created_at": "01-05-2020 17:38",
                    "modified_at": "01-05-2020 17:38",
                    "date": "2020-06-13",
                    "count_piglets_at_start": 444,
                    "tr_in_aka_weight_in_qnty": 690,
                    "tr_in_aka_weight_in_total": 5313.0,
                    "tr_in_aka_weight_in_avg": 7.705,
                    "tr_out_aka_weight_in_qnty": None,
                    "tr_out_aka_weight_in_total": None,
                    "tr_out_aka_weight_in_avg": None,
                    "padej_qnty": 2,
                    "padej_total_weight": 16.0,
                    "prirezka_qnty": 1,
                    "prirezka_total_weight": 9.0,
                    "vinuzhd_qnty": 0,
                    "vinuzhd_total_weight": 0.0,
                    "spec_qnty": 0,
                    "spec_total_weight": 0.0,
                    "tr_in_qnty": 690,
                    "tr_out_qnty": None
                },
                {
                    "id": 166,
                    "created_at": "01-05-2020 17:38",
                    "modified_at": "01-05-2020 17:38",
                    "date": "2020-06-14",
                    "count_piglets_at_start": 1131,
                    "tr_in_aka_weight_in_qnty": None,
                    "tr_in_aka_weight_in_total": None,
                    "tr_in_aka_weight_in_avg": None,
                    "tr_out_aka_weight_in_qnty": None,
                    "tr_out_aka_weight_in_total": None,
                    "tr_out_aka_weight_in_avg": None,
                    "padej_qnty": 0,
                    "padej_total_weight": 0.0,
                    "prirezka_qnty": 0,
                    "prirezka_total_weight": 0.0,
                    "vinuzhd_qnty": 0,
                    "vinuzhd_total_weight": 0.0,
                    "spec_qnty": 0,
                    "spec_total_weight": 0.0,
                    "tr_in_qnty": None,
                    "tr_out_qnty": None
                },
                {
                    "id": 167,
                    "created_at": "01-05-2020 17:38",
                    "modified_at": "01-05-2020 17:38",
                    "date": "2020-06-15",
                    "count_piglets_at_start": 1131,
                    "tr_in_aka_weight_in_qnty": None,
                    "tr_in_aka_weight_in_total": None,
                    "tr_in_aka_weight_in_avg": None,
                    "tr_out_aka_weight_in_qnty": None,
                    "tr_out_aka_weight_in_total": None,
                    "tr_out_aka_weight_in_avg": None,
                    "padej_qnty": 0,
                    "padej_total_weight": 0.0,
                    "prirezka_qnty": 0,
                    "prirezka_total_weight": 0.0,
                    "vinuzhd_qnty": 0,
                    "vinuzhd_total_weight": 0.0,
                    "spec_qnty": 0,
                    "spec_total_weight": 0.0,
                    "tr_in_qnty": None,
                    "tr_out_qnty": None
                },
                {
                    "id": 168,
                    "created_at": "01-05-2020 17:38",
                    "modified_at": "01-05-2020 17:38",
                    "date": "2020-06-16",
                    "count_piglets_at_start": 1131,
                    "tr_in_aka_weight_in_qnty": None,
                    "tr_in_aka_weight_in_total": None,
                    "tr_in_aka_weight_in_avg": None,
                    "tr_out_aka_weight_in_qnty": None,
                    "tr_out_aka_weight_in_total": None,
                    "tr_out_aka_weight_in_avg": None,
                    "padej_qnty": 0,
                    "padej_total_weight": 0.0,
                    "prirezka_qnty": 0,
                    "prirezka_total_weight": 0.0,
                    "vinuzhd_qnty": 0,
                    "vinuzhd_total_weight": 0.0,
                    "spec_qnty": 0,
                    "spec_total_weight": 0.0,
                    "tr_in_qnty": None,
                    "tr_out_qnty": None
                },
                {
                    "id": 169,
                    "created_at": "01-05-2020 17:38",
                    "modified_at": "01-05-2020 17:38",
                    "date": "2020-06-17",
                    "count_piglets_at_start": 1131,
                    "tr_in_aka_weight_in_qnty": None,
                    "tr_in_aka_weight_in_total": None,
                    "tr_in_aka_weight_in_avg": None,
                    "tr_out_aka_weight_in_qnty": 632,
                    "tr_out_aka_weight_in_total": 15230.0,
                    "tr_out_aka_weight_in_avg": 24.0233333333333,
                    "padej_qnty": 1,
                    "padej_total_weight": 14.0,
                    "prirezka_qnty": 1,
                    "prirezka_total_weight": 11.0,
                    "vinuzhd_qnty": 0,
                    "vinuzhd_total_weight": 0.0,
                    "spec_qnty": 0,
                    "spec_total_weight": 0.0,
                    "tr_in_qnty": None,
                    "tr_out_qnty": None
                },
                {
                    "id": 170,
                    "created_at": "01-05-2020 17:38",
                    "modified_at": "01-05-2020 17:38",
                    "date": "2020-06-18",
                    "count_piglets_at_start": 1129,
                    "tr_in_aka_weight_in_qnty": None,
                    "tr_in_aka_weight_in_total": None,
                    "tr_in_aka_weight_in_avg": None,
                    "tr_out_aka_weight_in_qnty": None,
                    "tr_out_aka_weight_in_total": None,
                    "tr_out_aka_weight_in_avg": None,
                    "padej_qnty": 0,
                    "padej_total_weight": 0.0,
                    "prirezka_qnty": 0,
                    "prirezka_total_weight": 0.0,
                    "vinuzhd_qnty": 0,
                    "vinuzhd_total_weight": 0.0,
                    "spec_qnty": 0,
                    "spec_total_weight": 0.0,
                    "tr_in_qnty": None,
                    "tr_out_qnty": 632
                },
                {
                    "id": 171,
                    "created_at": "01-05-2020 17:38",
                    "modified_at": "01-05-2020 17:38",
                    "date": "2020-06-19",
                    "count_piglets_at_start": 497,
                    "tr_in_aka_weight_in_qnty": 579,
                    "tr_in_aka_weight_in_total": 4458.6,
                    "tr_in_aka_weight_in_avg": 7.7,
                    "tr_out_aka_weight_in_qnty": None,
                    "tr_out_aka_weight_in_total": None,
                    "tr_out_aka_weight_in_avg": None,
                    "padej_qnty": 0,
                    "padej_total_weight": 0.0,
                    "prirezka_qnty": 3,
                    "prirezka_total_weight": 25.0,
                    "vinuzhd_qnty": 0,
                    "vinuzhd_total_weight": 0.0,
                    "spec_qnty": 0,
                    "spec_total_weight": 0.0,
                    "tr_in_qnty": None,
                    "tr_out_qnty": None
                },
                {
                    "id": 172,
                    "created_at": "01-05-2020 17:38",
                    "modified_at": "01-05-2020 17:38",
                    "date": "2020-06-20",
                    "count_piglets_at_start": 494,
                    "tr_in_aka_weight_in_qnty": None,
                    "tr_in_aka_weight_in_total": None,
                    "tr_in_aka_weight_in_avg": None,
                    "tr_out_aka_weight_in_qnty": None,
                    "tr_out_aka_weight_in_total": None,
                    "tr_out_aka_weight_in_avg": None,
                    "padej_qnty": 3,
                    "padej_total_weight": 23.0,
                    "prirezka_qnty": 0,
                    "prirezka_total_weight": 0.0,
                    "vinuzhd_qnty": 0,
                    "vinuzhd_total_weight": 0.0,
                    "spec_qnty": 0,
                    "spec_total_weight": 0.0,
                    "tr_in_qnty": 579,
                    "tr_out_qnty": None
                },
                {
                    "id": 173,
                    "created_at": "01-05-2020 17:38",
                    "modified_at": "01-05-2020 17:38",
                    "date": "2020-06-21",
                    "count_piglets_at_start": 1070,
                    "tr_in_aka_weight_in_qnty": None,
                    "tr_in_aka_weight_in_total": None,
                    "tr_in_aka_weight_in_avg": None,
                    "tr_out_aka_weight_in_qnty": None,
                    "tr_out_aka_weight_in_total": None,
                    "tr_out_aka_weight_in_avg": None,
                    "padej_qnty": 0,
                    "padej_total_weight": 0.0,
                    "prirezka_qnty": 0,
                    "prirezka_total_weight": 0.0,
                    "vinuzhd_qnty": 0,
                    "vinuzhd_total_weight": 0.0,
                    "spec_qnty": 0,
                    "spec_total_weight": 0.0,
                    "tr_in_qnty": None,
                    "tr_out_qnty": None
                },
                {
                    "id": 174,
                    "created_at": "01-05-2020 17:38",
                    "modified_at": "01-05-2020 17:38",
                    "date": "2020-06-22",
                    "count_piglets_at_start": 1070,
                    "tr_in_aka_weight_in_qnty": None,
                    "tr_in_aka_weight_in_total": None,
                    "tr_in_aka_weight_in_avg": None,
                    "tr_out_aka_weight_in_qnty": None,
                    "tr_out_aka_weight_in_total": None,
                    "tr_out_aka_weight_in_avg": None,
                    "padej_qnty": 0,
                    "padej_total_weight": 0.0,
                    "prirezka_qnty": 0,
                    "prirezka_total_weight": 0.0,
                    "vinuzhd_qnty": 0,
                    "vinuzhd_total_weight": 0.0,
                    "spec_qnty": 0,
                    "spec_total_weight": 0.0,
                    "tr_in_qnty": None,
                    "tr_out_qnty": None
                },
                {
                    "id": 175,
                    "created_at": "01-05-2020 17:38",
                    "modified_at": "01-05-2020 17:38",
                    "date": "2020-06-23",
                    "count_piglets_at_start": 1070,
                    "tr_in_aka_weight_in_qnty": None,
                    "tr_in_aka_weight_in_total": None,
                    "tr_in_aka_weight_in_avg": None,
                    "tr_out_aka_weight_in_qnty": None,
                    "tr_out_aka_weight_in_total": None,
                    "tr_out_aka_weight_in_avg": None,
                    "padej_qnty": 0,
                    "padej_total_weight": 0.0,
                    "prirezka_qnty": 0,
                    "prirezka_total_weight": 0.0,
                    "vinuzhd_qnty": 0,
                    "vinuzhd_total_weight": 0.0,
                    "spec_qnty": 0,
                    "spec_total_weight": 0.0,
                    "tr_in_qnty": None,
                    "tr_out_qnty": None
                },
                {
                    "id": 176,
                    "created_at": "01-05-2020 17:38",
                    "modified_at": "01-05-2020 17:38",
                    "date": "2020-06-24",
                    "count_piglets_at_start": 1070,
                    "tr_in_aka_weight_in_qnty": None,
                    "tr_in_aka_weight_in_total": None,
                    "tr_in_aka_weight_in_avg": None,
                    "tr_out_aka_weight_in_qnty": None,
                    "tr_out_aka_weight_in_total": None,
                    "tr_out_aka_weight_in_avg": None,
                    "padej_qnty": 2,
                    "padej_total_weight": 19.0,
                    "prirezka_qnty": 1,
                    "prirezka_total_weight": 10.0,
                    "vinuzhd_qnty": 10,
                    "vinuzhd_total_weight": 123.0,
                    "spec_qnty": 0,
                    "spec_total_weight": 0.0,
                    "tr_in_qnty": None,
                    "tr_out_qnty": None
                },
                {
                    "id": 177,
                    "created_at": "01-05-2020 17:38",
                    "modified_at": "01-05-2020 17:38",
                    "date": "2020-06-25",
                    "count_piglets_at_start": 1057,
                    "tr_in_aka_weight_in_qnty": None,
                    "tr_in_aka_weight_in_total": None,
                    "tr_in_aka_weight_in_avg": None,
                    "tr_out_aka_weight_in_qnty": 682,
                    "tr_out_aka_weight_in_total": 16020.0,
                    "tr_out_aka_weight_in_avg": 23.435,
                    "padej_qnty": 2,
                    "padej_total_weight": 26.0,
                    "prirezka_qnty": 1,
                    "prirezka_total_weight": 15.0,
                    "vinuzhd_qnty": 0,
                    "vinuzhd_total_weight": 0.0,
                    "spec_qnty": 0,
                    "spec_total_weight": 0.0,
                    "tr_in_qnty": 1,
                    "tr_out_qnty": 682
                },
                {
                    "id": 178,
                    "created_at": "01-05-2020 17:38",
                    "modified_at": "01-05-2020 17:38",
                    "date": "2020-06-26",
                    "count_piglets_at_start": 373,
                    "tr_in_aka_weight_in_qnty": None,
                    "tr_in_aka_weight_in_total": None,
                    "tr_in_aka_weight_in_avg": None,
                    "tr_out_aka_weight_in_qnty": None,
                    "tr_out_aka_weight_in_total": None,
                    "tr_out_aka_weight_in_avg": None,
                    "padej_qnty": 0,
                    "padej_total_weight": 0.0,
                    "prirezka_qnty": 0,
                    "prirezka_total_weight": 0.0,
                    "vinuzhd_qnty": 0,
                    "vinuzhd_total_weight": 0.0,
                    "spec_qnty": 0,
                    "spec_total_weight": 0.0,
                    "tr_in_qnty": None,
                    "tr_out_qnty": None
                },
                {
                    "id": 179,
                    "created_at": "01-05-2020 17:38",
                    "modified_at": "01-05-2020 17:38",
                    "date": "2020-06-27",
                    "count_piglets_at_start": 373,
                    "tr_in_aka_weight_in_qnty": None,
                    "tr_in_aka_weight_in_total": None,
                    "tr_in_aka_weight_in_avg": None,
                    "tr_out_aka_weight_in_qnty": None,
                    "tr_out_aka_weight_in_total": None,
                    "tr_out_aka_weight_in_avg": None,
                    "padej_qnty": 0,
                    "padej_total_weight": 0.0,
                    "prirezka_qnty": 0,
                    "prirezka_total_weight": 0.0,
                    "vinuzhd_qnty": 0,
                    "vinuzhd_total_weight": 0.0,
                    "spec_qnty": 0,
                    "spec_total_weight": 0.0,
                    "tr_in_qnty": None,
                    "tr_out_qnty": None
                },
                {
                    "id": 180,
                    "created_at": "01-05-2020 17:38",
                    "modified_at": "01-05-2020 17:38",
                    "date": "2020-06-28",
                    "count_piglets_at_start": 373,
                    "tr_in_aka_weight_in_qnty": None,
                    "tr_in_aka_weight_in_total": None,
                    "tr_in_aka_weight_in_avg": None,
                    "tr_out_aka_weight_in_qnty": None,
                    "tr_out_aka_weight_in_total": None,
                    "tr_out_aka_weight_in_avg": None,
                    "padej_qnty": 0,
                    "padej_total_weight": 0.0,
                    "prirezka_qnty": 0,
                    "prirezka_total_weight": 0.0,
                    "vinuzhd_qnty": 0,
                    "vinuzhd_total_weight": 0.0,
                    "spec_qnty": 0,
                    "spec_total_weight": 0.0,
                    "tr_in_qnty": 636,
                    "tr_out_qnty": None
                },
                {
                    "id": 181,
                    "created_at": "01-05-2020 17:38",
                    "modified_at": "01-05-2020 17:38",
                    "date": "2020-06-29",
                    "count_piglets_at_start": 1009,
                    "tr_in_aka_weight_in_qnty": None,
                    "tr_in_aka_weight_in_total": None,
                    "tr_in_aka_weight_in_avg": None,
                    "tr_out_aka_weight_in_qnty": None,
                    "tr_out_aka_weight_in_total": None,
                    "tr_out_aka_weight_in_avg": None,
                    "padej_qnty": 3,
                    "padej_total_weight": 38.0,
                    "prirezka_qnty": 3,
                    "prirezka_total_weight": 28.0,
                    "vinuzhd_qnty": 0,
                    "vinuzhd_total_weight": 0.0,
                    "spec_qnty": 0,
                    "spec_total_weight": 0.0,
                    "tr_in_qnty": None,
                    "tr_out_qnty": None
                },
                {
                    "id": 182,
                    "created_at": "01-05-2020 17:38",
                    "modified_at": "01-05-2020 17:38",
                    "date": "2020-06-30",
                    "count_piglets_at_start": 1003,
                    "tr_in_aka_weight_in_qnty": None,
                    "tr_in_aka_weight_in_total": None,
                    "tr_in_aka_weight_in_avg": None,
                    "tr_out_aka_weight_in_qnty": None,
                    "tr_out_aka_weight_in_total": None,
                    "tr_out_aka_weight_in_avg": None,
                    "padej_qnty": 0,
                    "padej_total_weight": 0.0,
                    "prirezka_qnty": 0,
                    "prirezka_total_weight": 0.0,
                    "vinuzhd_qnty": 0,
                    "vinuzhd_total_weight": 0.0,
                    "spec_qnty": 0,
                    "spec_total_weight": 0.0,
                    "tr_in_qnty": None,
                    "tr_out_qnty": None
                },
                {
                    "id": 183,
                    "created_at": "01-05-2020 17:38",
                    "modified_at": "01-05-2020 17:38",
                    "date": "2020-07-01",
                    "count_piglets_at_start": 1003,
                    "tr_in_aka_weight_in_qnty": None,
                    "tr_in_aka_weight_in_total": None,
                    "tr_in_aka_weight_in_avg": None,
                    "tr_out_aka_weight_in_qnty": None,
                    "tr_out_aka_weight_in_total": None,
                    "tr_out_aka_weight_in_avg": None,
                    "padej_qnty": 2,
                    "padej_total_weight": 30.0,
                    "prirezka_qnty": 0,
                    "prirezka_total_weight": 0.0,
                    "vinuzhd_qnty": 0,
                    "vinuzhd_total_weight": 0.0,
                    "spec_qnty": 0,
                    "spec_total_weight": 0.0,
                    "tr_in_qnty": None,
                    "tr_out_qnty": None
                },
                {
                    "id": 184,
                    "created_at": "01-05-2020 17:38",
                    "modified_at": "01-05-2020 17:38",
                    "date": "2020-07-02",
                    "count_piglets_at_start": 1001,
                    "tr_in_aka_weight_in_qnty": 636,
                    "tr_in_aka_weight_in_total": 4770.0,
                    "tr_in_aka_weight_in_avg": 7.5,
                    "tr_out_aka_weight_in_qnty": 641,
                    "tr_out_aka_weight_in_total": 14910.0,
                    "tr_out_aka_weight_in_avg": 23.2216666666667,
                    "padej_qnty": 1,
                    "padej_total_weight": 25.0,
                    "prirezka_qnty": 1,
                    "prirezka_total_weight": 20.0,
                    "vinuzhd_qnty": 0,
                    "vinuzhd_total_weight": 0.0,
                    "spec_qnty": 0,
                    "spec_total_weight": 0.0,
                    "tr_in_qnty": None,
                    "tr_out_qnty": 641
                },
                {
                    "id": 185,
                    "created_at": "01-05-2020 17:38",
                    "modified_at": "01-05-2020 17:38",
                    "date": "2020-07-03",
                    "count_piglets_at_start": 358,
                    "tr_in_aka_weight_in_qnty": None,
                    "tr_in_aka_weight_in_total": None,
                    "tr_in_aka_weight_in_avg": None,
                    "tr_out_aka_weight_in_qnty": None,
                    "tr_out_aka_weight_in_total": None,
                    "tr_out_aka_weight_in_avg": None,
                    "padej_qnty": 0,
                    "padej_total_weight": 0.0,
                    "prirezka_qnty": 0,
                    "prirezka_total_weight": 0.0,
                    "vinuzhd_qnty": 0,
                    "vinuzhd_total_weight": 0.0,
                    "spec_qnty": 0,
                    "spec_total_weight": 0.0,
                    "tr_in_qnty": None,
                    "tr_out_qnty": None
                },
                {
                    "id": 186,
                    "created_at": "01-05-2020 17:38",
                    "modified_at": "01-05-2020 17:38",
                    "date": "2020-07-04",
                    "count_piglets_at_start": 358,
                    "tr_in_aka_weight_in_qnty": 655,
                    "tr_in_aka_weight_in_total": 5197.0,
                    "tr_in_aka_weight_in_avg": 7.88,
                    "tr_out_aka_weight_in_qnty": None,
                    "tr_out_aka_weight_in_total": None,
                    "tr_out_aka_weight_in_avg": None,
                    "padej_qnty": 1,
                    "padej_total_weight": 8.0,
                    "prirezka_qnty": 4,
                    "prirezka_total_weight": 30.0,
                    "vinuzhd_qnty": 0,
                    "vinuzhd_total_weight": 0.0,
                    "spec_qnty": 0,
                    "spec_total_weight": 0.0,
                    "tr_in_qnty": 655,
                    "tr_out_qnty": None
                },
                {
                    "id": 187,
                    "created_at": "01-05-2020 17:38",
                    "modified_at": "01-05-2020 17:38",
                    "date": "2020-07-05",
                    "count_piglets_at_start": 1008,
                    "tr_in_aka_weight_in_qnty": None,
                    "tr_in_aka_weight_in_total": None,
                    "tr_in_aka_weight_in_avg": None,
                    "tr_out_aka_weight_in_qnty": None,
                    "tr_out_aka_weight_in_total": None,
                    "tr_out_aka_weight_in_avg": None,
                    "padej_qnty": 1,
                    "padej_total_weight": 8.0,
                    "prirezka_qnty": 0,
                    "prirezka_total_weight": 0.0,
                    "vinuzhd_qnty": 0,
                    "vinuzhd_total_weight": 0.0,
                    "spec_qnty": 0,
                    "spec_total_weight": 0.0,
                    "tr_in_qnty": None,
                    "tr_out_qnty": None
                },
                {
                    "id": 188,
                    "created_at": "01-05-2020 17:38",
                    "modified_at": "01-05-2020 17:38",
                    "date": "2020-07-06",
                    "count_piglets_at_start": 1007,
                    "tr_in_aka_weight_in_qnty": None,
                    "tr_in_aka_weight_in_total": None,
                    "tr_in_aka_weight_in_avg": None,
                    "tr_out_aka_weight_in_qnty": None,
                    "tr_out_aka_weight_in_total": None,
                    "tr_out_aka_weight_in_avg": None,
                    "padej_qnty": 4,
                    "padej_total_weight": 25.0,
                    "prirezka_qnty": 3,
                    "prirezka_total_weight": 28.0,
                    "vinuzhd_qnty": 0,
                    "vinuzhd_total_weight": 0.0,
                    "spec_qnty": 0,
                    "spec_total_weight": 0.0,
                    "tr_in_qnty": None,
                    "tr_out_qnty": None
                },
                {
                    "id": 189,
                    "created_at": "01-05-2020 17:38",
                    "modified_at": "01-05-2020 17:38",
                    "date": "2020-07-07",
                    "count_piglets_at_start": 1000,
                    "tr_in_aka_weight_in_qnty": None,
                    "tr_in_aka_weight_in_total": None,
                    "tr_in_aka_weight_in_avg": None,
                    "tr_out_aka_weight_in_qnty": None,
                    "tr_out_aka_weight_in_total": None,
                    "tr_out_aka_weight_in_avg": None,
                    "padej_qnty": 1,
                    "padej_total_weight": 10.0,
                    "prirezka_qnty": 0,
                    "prirezka_total_weight": 0.0,
                    "vinuzhd_qnty": 0,
                    "vinuzhd_total_weight": 0.0,
                    "spec_qnty": 0,
                    "spec_total_weight": 0.0,
                    "tr_in_qnty": None,
                    "tr_out_qnty": None
                },
                {
                    "id": 190,
                    "created_at": "01-05-2020 17:38",
                    "modified_at": "01-05-2020 17:38",
                    "date": "2020-07-08",
                    "count_piglets_at_start": 999,
                    "tr_in_aka_weight_in_qnty": None,
                    "tr_in_aka_weight_in_total": None,
                    "tr_in_aka_weight_in_avg": None,
                    "tr_out_aka_weight_in_qnty": None,
                    "tr_out_aka_weight_in_total": None,
                    "tr_out_aka_weight_in_avg": None,
                    "padej_qnty": 1,
                    "padej_total_weight": 9.0,
                    "prirezka_qnty": 1,
                    "prirezka_total_weight": 10.0,
                    "vinuzhd_qnty": 0,
                    "vinuzhd_total_weight": 0.0,
                    "spec_qnty": 0,
                    "spec_total_weight": 0.0,
                    "tr_in_qnty": None,
                    "tr_out_qnty": None
                },
                {
                    "id": 191,
                    "created_at": "01-05-2020 17:38",
                    "modified_at": "01-05-2020 17:38",
                    "date": "2020-07-09",
                    "count_piglets_at_start": 997,
                    "tr_in_aka_weight_in_qnty": None,
                    "tr_in_aka_weight_in_total": None,
                    "tr_in_aka_weight_in_avg": None,
                    "tr_out_aka_weight_in_qnty": 677,
                    "tr_out_aka_weight_in_total": 15950.0,
                    "tr_out_aka_weight_in_avg": 23.595,
                    "padej_qnty": 3,
                    "padej_total_weight": 19.0,
                    "prirezka_qnty": 1,
                    "prirezka_total_weight": 5.0,
                    "vinuzhd_qnty": 0,
                    "vinuzhd_total_weight": 0.0,
                    "spec_qnty": 0,
                    "spec_total_weight": 0.0,
                    "tr_in_qnty": None,
                    "tr_out_qnty": 677
                },
                {
                    "id": 192,
                    "created_at": "01-05-2020 17:38",
                    "modified_at": "01-05-2020 17:38",
                    "date": "2020-07-10",
                    "count_piglets_at_start": 316,
                    "tr_in_aka_weight_in_qnty": None,
                    "tr_in_aka_weight_in_total": None,
                    "tr_in_aka_weight_in_avg": None,
                    "tr_out_aka_weight_in_qnty": None,
                    "tr_out_aka_weight_in_total": None,
                    "tr_out_aka_weight_in_avg": None,
                    "padej_qnty": 1,
                    "padej_total_weight": 9.0,
                    "prirezka_qnty": 0,
                    "prirezka_total_weight": 0.0,
                    "vinuzhd_qnty": 5,
                    "vinuzhd_total_weight": 80.0,
                    "spec_qnty": 0,
                    "spec_total_weight": 0.0,
                    "tr_in_qnty": None,
                    "tr_out_qnty": None
                },
                {
                    "id": 193,
                    "created_at": "01-05-2020 17:38",
                    "modified_at": "01-05-2020 17:38",
                    "date": "2020-07-11",
                    "count_piglets_at_start": 310,
                    "tr_in_aka_weight_in_qnty": 694,
                    "tr_in_aka_weight_in_total": 5321.0,
                    "tr_in_aka_weight_in_avg": 7.65833333333333,
                    "tr_out_aka_weight_in_qnty": None,
                    "tr_out_aka_weight_in_total": None,
                    "tr_out_aka_weight_in_avg": None,
                    "padej_qnty": 0,
                    "padej_total_weight": 0.0,
                    "prirezka_qnty": 0,
                    "prirezka_total_weight": 0.0,
                    "vinuzhd_qnty": 0,
                    "vinuzhd_total_weight": 0.0,
                    "spec_qnty": 0,
                    "spec_total_weight": 0.0,
                    "tr_in_qnty": 694,
                    "tr_out_qnty": None
                },
                {
                    "id": 194,
                    "created_at": "01-05-2020 17:38",
                    "modified_at": "01-05-2020 17:38",
                    "date": "2020-07-12",
                    "count_piglets_at_start": 1004,
                    "tr_in_aka_weight_in_qnty": None,
                    "tr_in_aka_weight_in_total": None,
                    "tr_in_aka_weight_in_avg": None,
                    "tr_out_aka_weight_in_qnty": None,
                    "tr_out_aka_weight_in_total": None,
                    "tr_out_aka_weight_in_avg": None,
                    "padej_qnty": 2,
                    "padej_total_weight": 14.0,
                    "prirezka_qnty": 0,
                    "prirezka_total_weight": 0.0,
                    "vinuzhd_qnty": 0,
                    "vinuzhd_total_weight": 0.0,
                    "spec_qnty": 0,
                    "spec_total_weight": 0.0,
                    "tr_in_qnty": None,
                    "tr_out_qnty": None
                },
                {
                    "id": 195,
                    "created_at": "01-05-2020 17:38",
                    "modified_at": "01-05-2020 17:38",
                    "date": "2020-07-13",
                    "count_piglets_at_start": 1002,
                    "tr_in_aka_weight_in_qnty": None,
                    "tr_in_aka_weight_in_total": None,
                    "tr_in_aka_weight_in_avg": None,
                    "tr_out_aka_weight_in_qnty": None,
                    "tr_out_aka_weight_in_total": None,
                    "tr_out_aka_weight_in_avg": None,
                    "padej_qnty": 2,
                    "padej_total_weight": 20.0,
                    "prirezka_qnty": 1,
                    "prirezka_total_weight": 7.0,
                    "vinuzhd_qnty": 0,
                    "vinuzhd_total_weight": 0.0,
                    "spec_qnty": 0,
                    "spec_total_weight": 0.0,
                    "tr_in_qnty": None,
                    "tr_out_qnty": None
                }
            ],
            "total_info": {
                "total_tr_in_aka_weight_in_qnty": 3254,
                "total_tr_in_aka_weight_in_total": 25059.6,
                "total_tr_in_aka_weight_in_avg": 7.68866666666667,
                "total_tr_out_aka_weight_in_qnty": 2632,
                "total_tr_out_aka_weight_in_total": 62110.0,
                "total_tr_out_aka_weight_in_avg": 23.56875,
                "total_tr_in_qnty": 3255,
                "total_tr_out_qnty": 2632,
                "total_padej_qnty": 32,
                "total_padej_total_weight": 313.0,
                "total_prirezka_qnty": 21,
                "total_prirezka_total_weight": 198.0,
                "total_vinuzhd_qnty": 15,
                "total_vinuzhd_total_weight": 203.0,
                "total_spec_qnty": 0,
                "total_spec_total_weight": 0.0
            }
        }
    
    @tag('with_file')
    def test_export_to_excel_ws3(self):
        export_to_excel_ws3(filename='../data/ws3header.xlsx', data=self.data_ws3)

    @tag('with_file')
    def test_export_to_excel_ws(self):
        export_to_excel_ws(data=self.data_ws, ws_number=4)