# -*- coding: utf-8 -*-
from xlrd import open_workbook, xldate_as_tuple
from datetime import timedelta, date, datetime

from django.test import TestCase
from django.utils import timezone
from django.test import tag

from core.utils import export_to_excel_ws3

import locations.testing_utils as locaions_testing
import sows.testing_utils as sows_testings
import sows_events.utils as sows_events_testings
import staff.testing_utils as staff_testings

from sows.models import Sow
from sows_events.models import SowFarrow, CullingSow
from piglets.models import Piglets
from piglets_events.models import CullingPiglets, WeighingPiglets
from transactions.models import SowTransaction, PigletsTransaction
from locations.models import Location
from reports.models import ReportDate
from reports.serializers import ReportDateWs3Serializer


class ExportToExcelTest(TestCase):
    def setUp(self):
        locaions_testing.create_workshops_sections_and_cells()
        sows_testings.create_statuses()
        sows_events_testings.create_types()
        staff_testings.create_svinbin_users()

        self.data = {
    "results": [
        {
            "id": 122,
            "count_sows_ws3_start_date": {
                "suporos": 53,
                "suporos2": 53,
                "podsos": 206,
                "podsos2": "206 , 0 , 0"
            },
            "created_at": "01-05-2020 17:38",
            "modified_at": "01-05-2020 17:38",
            "date": "2020-05-01",
            "padej_sup_count": None,
            "padej_sup_weight": None,
            "padej_podsos_count": None,
            "padej_podsos_weight": None,
            "vinuzhd_sup_count": None,
            "vinuzhd_sup_weight": None,
            "vinuzhd_podsos_count": None,
            "vinuzhd_podsos_weight": None,
            "tr_in_from_1_sup_count": None,
            "tr_in_from_2_sup_count": None,
            "tr_in_podsos_count": None,
            "tr_out_sup_count": None,
            "tr_out_podsos_count": 4,
            "count_oporos": None,
            "count_alive": None,
            "count_piglets_at_start": 471,
            "tr_out_aka_weight_qnty": None,
            "tr_out_aka_weight_total": None,
            "tr_out_aka_weight_avg": None,
            "piglets_padej_qnty": 8,
            "piglets_vinuzhd_qnty": None,
            "piglets_padej_weight": 0.0,
            "piglets_vinuzhd_weight": None
        },
        {
            "id": 123,
            "count_sows_ws3_start_date": {
                "suporos": 53,
                "suporos2": 53,
                "podsos": 202,
                "podsos2": "202 , 0 , 0"
            },
            "created_at": "01-05-2020 17:38",
            "modified_at": "01-05-2020 17:38",
            "date": "2020-05-02",
            "padej_sup_count": None,
            "padej_sup_weight": None,
            "padej_podsos_count": None,
            "padej_podsos_weight": None,
            "vinuzhd_sup_count": None,
            "vinuzhd_sup_weight": None,
            "vinuzhd_podsos_count": None,
            "vinuzhd_podsos_weight": None,
            "tr_in_from_1_sup_count": None,
            "tr_in_from_2_sup_count": 65,
            "tr_in_podsos_count": None,
            "tr_out_sup_count": None,
            "tr_out_podsos_count": None,
            "count_oporos": 23,
            "count_alive": 255,
            "count_piglets_at_start": 463,
            "tr_out_aka_weight_qnty": 637,
            "tr_out_aka_weight_total": 5235.0,
            "tr_out_aka_weight_avg": 8.27333333333333,
            "piglets_padej_qnty": 5,
            "piglets_vinuzhd_qnty": None,
            "piglets_padej_weight": 0.0,
            "piglets_vinuzhd_weight": None
        },
        {
            "id": 124,
            "count_sows_ws3_start_date": {
                "suporos": 96,
                "suporos2": 96,
                "podsos": 225,
                "podsos2": "177 , 48 , 0"
            },
            "created_at": "01-05-2020 17:38",
            "modified_at": "01-05-2020 17:38",
            "date": "2020-05-03",
            "padej_sup_count": None,
            "padej_sup_weight": None,
            "padej_podsos_count": None,
            "padej_podsos_weight": None,
            "vinuzhd_sup_count": None,
            "vinuzhd_sup_weight": None,
            "vinuzhd_podsos_count": None,
            "vinuzhd_podsos_weight": None,
            "tr_in_from_1_sup_count": None,
            "tr_in_from_2_sup_count": None,
            "tr_in_podsos_count": None,
            "tr_out_sup_count": None,
            "tr_out_podsos_count": 47,
            "count_oporos": 5,
            "count_alive": 44,
            "count_piglets_at_start": 76,
            "tr_out_aka_weight_qnty": None,
            "tr_out_aka_weight_total": None,
            "tr_out_aka_weight_avg": None,
            "piglets_padej_qnty": 6,
            "piglets_vinuzhd_qnty": None,
            "piglets_padej_weight": 0.0,
            "piglets_vinuzhd_weight": None
        },
        {
            "id": 125,
            "count_sows_ws3_start_date": {
                "suporos": 91,
                "suporos2": 91,
                "podsos": 185,
                "podsos2": "181 , 4 , 0"
            },
            "created_at": "01-05-2020 17:38",
            "modified_at": "01-05-2020 17:38",
            "date": "2020-05-04",
            "padej_sup_count": 3,
            "padej_sup_weight": None,
            "padej_podsos_count": None,
            "padej_podsos_weight": None,
            "vinuzhd_sup_count": None,
            "vinuzhd_sup_weight": None,
            "vinuzhd_podsos_count": None,
            "vinuzhd_podsos_weight": None,
            "tr_in_from_1_sup_count": None,
            "tr_in_from_2_sup_count": None,
            "tr_in_podsos_count": None,
            "tr_out_sup_count": None,
            "tr_out_podsos_count": 3,
            "count_oporos": 9,
            "count_alive": 88,
            "count_piglets_at_start": 114,
            "tr_out_aka_weight_qnty": None,
            "tr_out_aka_weight_total": None,
            "tr_out_aka_weight_avg": None,
            "piglets_padej_qnty": 7,
            "piglets_vinuzhd_qnty": None,
            "piglets_padej_weight": 0.0,
            "piglets_vinuzhd_weight": None
        },
        {
            "id": 126,
            "count_sows_ws3_start_date": {
                "suporos": 78,
                "suporos2": 78,
                "podsos": 192,
                "podsos2": "188 , 4 , 0"
            },
            "created_at": "01-05-2020 17:38",
            "modified_at": "01-05-2020 17:38",
            "date": "2020-05-05",
            "padej_sup_count": None,
            "padej_sup_weight": None,
            "padej_podsos_count": None,
            "padej_podsos_weight": None,
            "vinuzhd_sup_count": None,
            "vinuzhd_sup_weight": None,
            "vinuzhd_podsos_count": None,
            "vinuzhd_podsos_weight": None,
            "tr_in_from_1_sup_count": None,
            "tr_in_from_2_sup_count": None,
            "tr_in_podsos_count": None,
            "tr_out_sup_count": None,
            "tr_out_podsos_count": None,
            "count_oporos": 6,
            "count_alive": 51,
            "count_piglets_at_start": 195,
            "tr_out_aka_weight_qnty": None,
            "tr_out_aka_weight_total": None,
            "tr_out_aka_weight_avg": None,
            "piglets_padej_qnty": 7,
            "piglets_vinuzhd_qnty": None,
            "piglets_padej_weight": 0.0,
            "piglets_vinuzhd_weight": None
        },
        {
            "id": 127,
            "count_sows_ws3_start_date": {
                "suporos": 72,
                "suporos2": 72,
                "podsos": 198,
                "podsos2": "194 , 4 , 0"
            },
            "created_at": "01-05-2020 17:38",
            "modified_at": "01-05-2020 17:38",
            "date": "2020-05-06",
            "padej_sup_count": None,
            "padej_sup_weight": None,
            "padej_podsos_count": None,
            "padej_podsos_weight": None,
            "vinuzhd_sup_count": None,
            "vinuzhd_sup_weight": None,
            "vinuzhd_podsos_count": None,
            "vinuzhd_podsos_weight": None,
            "tr_in_from_1_sup_count": None,
            "tr_in_from_2_sup_count": 1,
            "tr_in_podsos_count": None,
            "tr_out_sup_count": None,
            "tr_out_podsos_count": 6,
            "count_oporos": 9,
            "count_alive": 112,
            "count_piglets_at_start": 239,
            "tr_out_aka_weight_qnty": 617,
            "tr_out_aka_weight_total": 4649.0,
            "tr_out_aka_weight_avg": 7.57833333333333,
            "piglets_padej_qnty": 12,
            "piglets_vinuzhd_qnty": None,
            "piglets_padej_weight": 0.0,
            "piglets_vinuzhd_weight": None
        },
        {
            "id": 128,
            "count_sows_ws3_start_date": {
                "suporos": 59,
                "suporos2": 59,
                "podsos": 206,
                "podsos2": "202 , 4 , 0"
            },
            "created_at": "01-05-2020 17:38",
            "modified_at": "01-05-2020 17:38",
            "date": "2020-05-07",
            "padej_sup_count": None,
            "padej_sup_weight": None,
            "padej_podsos_count": 2,
            "padej_podsos_weight": None,
            "vinuzhd_sup_count": None,
            "vinuzhd_sup_weight": None,
            "vinuzhd_podsos_count": None,
            "vinuzhd_podsos_weight": None,
            "tr_in_from_1_sup_count": None,
            "tr_in_from_2_sup_count": None,
            "tr_in_podsos_count": None,
            "tr_out_sup_count": None,
            "tr_out_podsos_count": None,
            "count_oporos": 1,
            "count_alive": 7,
            "count_piglets_at_start": -278,
            "tr_out_aka_weight_qnty": None,
            "tr_out_aka_weight_total": None,
            "tr_out_aka_weight_avg": None,
            "piglets_padej_qnty": 12,
            "piglets_vinuzhd_qnty": None,
            "piglets_padej_weight": 0.0,
            "piglets_vinuzhd_weight": None
        },
        {
            "id": 129,
            "count_sows_ws3_start_date": {
                "suporos": 58,
                "suporos2": 58,
                "podsos": 205,
                "podsos2": "201 , 4 , 0"
            },
            "created_at": "01-05-2020 17:38",
            "modified_at": "01-05-2020 17:38",
            "date": "2020-05-08",
            "padej_sup_count": None,
            "padej_sup_weight": None,
            "padej_podsos_count": None,
            "padej_podsos_weight": None,
            "vinuzhd_sup_count": None,
            "vinuzhd_sup_weight": None,
            "vinuzhd_podsos_count": None,
            "vinuzhd_podsos_weight": None,
            "tr_in_from_1_sup_count": None,
            "tr_in_from_2_sup_count": None,
            "tr_in_podsos_count": None,
            "tr_out_sup_count": None,
            "tr_out_podsos_count": 5,
            "count_oporos": 8,
            "count_alive": 94,
            "count_piglets_at_start": -283,
            "tr_out_aka_weight_qnty": None,
            "tr_out_aka_weight_total": None,
            "tr_out_aka_weight_avg": None,
            "piglets_padej_qnty": 10,
            "piglets_vinuzhd_qnty": None,
            "piglets_padej_weight": 0.0,
            "piglets_vinuzhd_weight": None
        },
        {
            "id": 130,
            "count_sows_ws3_start_date": {
                "suporos": 50,
                "suporos2": 50,
                "podsos": 208,
                "podsos2": "204 , 4 , 0"
            },
            "created_at": "01-05-2020 17:38",
            "modified_at": "01-05-2020 17:38",
            "date": "2020-05-09",
            "padej_sup_count": 1,
            "padej_sup_weight": None,
            "padej_podsos_count": 1,
            "padej_podsos_weight": None,
            "vinuzhd_sup_count": None,
            "vinuzhd_sup_weight": None,
            "vinuzhd_podsos_count": None,
            "vinuzhd_podsos_weight": None,
            "tr_in_from_1_sup_count": None,
            "tr_in_from_2_sup_count": 62,
            "tr_in_podsos_count": 1,
            "tr_out_sup_count": None,
            "tr_out_podsos_count": 54,
            "count_oporos": 41,
            "count_alive": 452,
            "count_piglets_at_start": -199,
            "tr_out_aka_weight_qnty": None,
            "tr_out_aka_weight_total": None,
            "tr_out_aka_weight_avg": None,
            "piglets_padej_qnty": 19,
            "piglets_vinuzhd_qnty": None,
            "piglets_padej_weight": 0.0,
            "piglets_vinuzhd_weight": None
        },
        {
            "id": 131,
            "count_sows_ws3_start_date": {
                "suporos": 71,
                "suporos2": 71,
                "podsos": 194,
                "podsos2": "187 , 7 , 0"
            },
            "created_at": "01-05-2020 17:38",
            "modified_at": "01-05-2020 17:38",
            "date": "2020-05-10",
            "padej_sup_count": 1,
            "padej_sup_weight": None,
            "padej_podsos_count": None,
            "padej_podsos_weight": None,
            "vinuzhd_sup_count": None,
            "vinuzhd_sup_weight": None,
            "vinuzhd_podsos_count": None,
            "vinuzhd_podsos_weight": None,
            "tr_in_from_1_sup_count": None,
            "tr_in_from_2_sup_count": None,
            "tr_in_podsos_count": None,
            "tr_out_sup_count": None,
            "tr_out_podsos_count": None,
            "count_oporos": None,
            "count_alive": None,
            "count_piglets_at_start": 234,
            "tr_out_aka_weight_qnty": None,
            "tr_out_aka_weight_total": None,
            "tr_out_aka_weight_avg": None,
            "piglets_padej_qnty": 5,
            "piglets_vinuzhd_qnty": None,
            "piglets_padej_weight": 0.0,
            "piglets_vinuzhd_weight": None
        },
        {
            "id": 132,
            "count_sows_ws3_start_date": {
                "suporos": 70,
                "suporos2": 70,
                "podsos": 194,
                "podsos2": "187 , 7 , 0"
            },
            "created_at": "01-05-2020 17:38",
            "modified_at": "01-05-2020 17:38",
            "date": "2020-05-11",
            "padej_sup_count": 1,
            "padej_sup_weight": None,
            "padej_podsos_count": None,
            "padej_podsos_weight": None,
            "vinuzhd_sup_count": None,
            "vinuzhd_sup_weight": None,
            "vinuzhd_podsos_count": None,
            "vinuzhd_podsos_weight": None,
            "tr_in_from_1_sup_count": None,
            "tr_in_from_2_sup_count": None,
            "tr_in_podsos_count": None,
            "tr_out_sup_count": None,
            "tr_out_podsos_count": None,
            "count_oporos": 9,
            "count_alive": 101,
            "count_piglets_at_start": 229,
            "tr_out_aka_weight_qnty": None,
            "tr_out_aka_weight_total": None,
            "tr_out_aka_weight_avg": None,
            "piglets_padej_qnty": 15,
            "piglets_vinuzhd_qnty": None,
            "piglets_padej_weight": 0.0,
            "piglets_vinuzhd_weight": None
        },
        {
            "id": 133,
            "count_sows_ws3_start_date": {
                "suporos": 60,
                "suporos2": 60,
                "podsos": 203,
                "podsos2": "196 , 7 , 0"
            },
            "created_at": "01-05-2020 17:38",
            "modified_at": "01-05-2020 17:38",
            "date": "2020-05-12",
            "padej_sup_count": None,
            "padej_sup_weight": None,
            "padej_podsos_count": None,
            "padej_podsos_weight": None,
            "vinuzhd_sup_count": None,
            "vinuzhd_sup_weight": None,
            "vinuzhd_podsos_count": None,
            "vinuzhd_podsos_weight": None,
            "tr_in_from_1_sup_count": None,
            "tr_in_from_2_sup_count": None,
            "tr_in_podsos_count": None,
            "tr_out_sup_count": None,
            "tr_out_podsos_count": None,
            "count_oporos": 5,
            "count_alive": 64,
            "count_piglets_at_start": 315,
            "tr_out_aka_weight_qnty": None,
            "tr_out_aka_weight_total": None,
            "tr_out_aka_weight_avg": None,
            "piglets_padej_qnty": 10,
            "piglets_vinuzhd_qnty": None,
            "piglets_padej_weight": 0.0,
            "piglets_vinuzhd_weight": None
        },
        {
            "id": 134,
            "count_sows_ws3_start_date": {
                "suporos": 55,
                "suporos2": 55,
                "podsos": 208,
                "podsos2": "201 , 7 , 0"
            },
            "created_at": "01-05-2020 17:38",
            "modified_at": "01-05-2020 17:38",
            "date": "2020-05-13",
            "padej_sup_count": None,
            "padej_sup_weight": None,
            "padej_podsos_count": None,
            "padej_podsos_weight": None,
            "vinuzhd_sup_count": None,
            "vinuzhd_sup_weight": None,
            "vinuzhd_podsos_count": None,
            "vinuzhd_podsos_weight": None,
            "tr_in_from_1_sup_count": None,
            "tr_in_from_2_sup_count": None,
            "tr_in_podsos_count": None,
            "tr_out_sup_count": None,
            "tr_out_podsos_count": None,
            "count_oporos": 10,
            "count_alive": 116,
            "count_piglets_at_start": 369,
            "tr_out_aka_weight_qnty": None,
            "tr_out_aka_weight_total": None,
            "tr_out_aka_weight_avg": None,
            "piglets_padej_qnty": 12,
            "piglets_vinuzhd_qnty": None,
            "piglets_padej_weight": 0.0,
            "piglets_vinuzhd_weight": None
        },
        {
            "id": 135,
            "count_sows_ws3_start_date": {
                "suporos": 45,
                "suporos2": 45,
                "podsos": 218,
                "podsos2": "211 , 7 , 0"
            },
            "created_at": "01-05-2020 17:38",
            "modified_at": "01-05-2020 17:38",
            "date": "2020-05-14",
            "padej_sup_count": None,
            "padej_sup_weight": None,
            "padej_podsos_count": None,
            "padej_podsos_weight": None,
            "vinuzhd_sup_count": None,
            "vinuzhd_sup_weight": None,
            "vinuzhd_podsos_count": None,
            "vinuzhd_podsos_weight": None,
            "tr_in_from_1_sup_count": None,
            "tr_in_from_2_sup_count": None,
            "tr_in_podsos_count": None,
            "tr_out_sup_count": None,
            "tr_out_podsos_count": None,
            "count_oporos": None,
            "count_alive": None,
            "count_piglets_at_start": 473,
            "tr_out_aka_weight_qnty": None,
            "tr_out_aka_weight_total": None,
            "tr_out_aka_weight_avg": None,
            "piglets_padej_qnty": 10,
            "piglets_vinuzhd_qnty": None,
            "piglets_padej_weight": 0.0,
            "piglets_vinuzhd_weight": None
        },
        {
            "id": 136,
            "count_sows_ws3_start_date": {
                "suporos": 46,
                "suporos2": 46,
                "podsos": 218,
                "podsos2": "211 , 7 , 0"
            },
            "created_at": "01-05-2020 17:38",
            "modified_at": "01-05-2020 17:38",
            "date": "2020-05-15",
            "padej_sup_count": 1,
            "padej_sup_weight": None,
            "padej_podsos_count": 2,
            "padej_podsos_weight": None,
            "vinuzhd_sup_count": None,
            "vinuzhd_sup_weight": None,
            "vinuzhd_podsos_count": None,
            "vinuzhd_podsos_weight": None,
            "tr_in_from_1_sup_count": None,
            "tr_in_from_2_sup_count": None,
            "tr_in_podsos_count": None,
            "tr_out_sup_count": None,
            "tr_out_podsos_count": 2,
            "count_oporos": 21,
            "count_alive": 251,
            "count_piglets_at_start": 463,
            "tr_out_aka_weight_qnty": 590,
            "tr_out_aka_weight_total": 4506.0,
            "tr_out_aka_weight_avg": 7.636,
            "piglets_padej_qnty": 11,
            "piglets_vinuzhd_qnty": None,
            "piglets_padej_weight": 0.0,
            "piglets_vinuzhd_weight": None
        },
        {
            "id": 137,
            "count_sows_ws3_start_date": {
                "suporos": 24,
                "suporos2": 24,
                "podsos": 235,
                "podsos2": "228 , 6 , 1"
            },
            "created_at": "01-05-2020 17:38",
            "modified_at": "01-05-2020 17:38",
            "date": "2020-05-16",
            "padej_sup_count": None,
            "padej_sup_weight": None,
            "padej_podsos_count": 1,
            "padej_podsos_weight": None,
            "vinuzhd_sup_count": None,
            "vinuzhd_sup_weight": None,
            "vinuzhd_podsos_count": None,
            "vinuzhd_podsos_weight": None,
            "tr_in_from_1_sup_count": None,
            "tr_in_from_2_sup_count": None,
            "tr_in_podsos_count": None,
            "tr_out_sup_count": None,
            "tr_out_podsos_count": 49,
            "count_oporos": 4,
            "count_alive": 49,
            "count_piglets_at_start": 113,
            "tr_out_aka_weight_qnty": None,
            "tr_out_aka_weight_total": None,
            "tr_out_aka_weight_avg": None,
            "piglets_padej_qnty": 10,
            "piglets_vinuzhd_qnty": None,
            "piglets_padej_weight": 0.0,
            "piglets_vinuzhd_weight": None
        },
        {
            "id": 138,
            "count_sows_ws3_start_date": {
                "suporos": 20,
                "suporos2": 20,
                "podsos": 190,
                "podsos2": "187 , 2 , 1"
            },
            "created_at": "01-05-2020 17:38",
            "modified_at": "01-05-2020 17:38",
            "date": "2020-05-17",
            "padej_sup_count": None,
            "padej_sup_weight": None,
            "padej_podsos_count": None,
            "padej_podsos_weight": None,
            "vinuzhd_sup_count": None,
            "vinuzhd_sup_weight": None,
            "vinuzhd_podsos_count": None,
            "vinuzhd_podsos_weight": None,
            "tr_in_from_1_sup_count": None,
            "tr_in_from_2_sup_count": None,
            "tr_in_podsos_count": None,
            "tr_out_sup_count": None,
            "tr_out_podsos_count": None,
            "count_oporos": 3,
            "count_alive": 32,
            "count_piglets_at_start": 152,
            "tr_out_aka_weight_qnty": None,
            "tr_out_aka_weight_total": None,
            "tr_out_aka_weight_avg": None,
            "piglets_padej_qnty": 6,
            "piglets_vinuzhd_qnty": None,
            "piglets_padej_weight": 0.0,
            "piglets_vinuzhd_weight": None
        },
        {
            "id": 139,
            "count_sows_ws3_start_date": {
                "suporos": 17,
                "suporos2": 17,
                "podsos": 193,
                "podsos2": "190 , 2 , 1"
            },
            "created_at": "01-05-2020 17:38",
            "modified_at": "01-05-2020 17:38",
            "date": "2020-05-18",
            "padej_sup_count": 1,
            "padej_sup_weight": None,
            "padej_podsos_count": 2,
            "padej_podsos_weight": None,
            "vinuzhd_sup_count": None,
            "vinuzhd_sup_weight": None,
            "vinuzhd_podsos_count": None,
            "vinuzhd_podsos_weight": None,
            "tr_in_from_1_sup_count": None,
            "tr_in_from_2_sup_count": 59,
            "tr_in_podsos_count": None,
            "tr_out_sup_count": None,
            "tr_out_podsos_count": None,
            "count_oporos": 1,
            "count_alive": 13,
            "count_piglets_at_start": 178,
            "tr_out_aka_weight_qnty": None,
            "tr_out_aka_weight_total": None,
            "tr_out_aka_weight_avg": None,
            "piglets_padej_qnty": 8,
            "piglets_vinuzhd_qnty": None,
            "piglets_padej_weight": 0.0,
            "piglets_vinuzhd_weight": None
        },
        {
            "id": 140,
            "count_sows_ws3_start_date": {
                "suporos": 74,
                "suporos2": 74,
                "podsos": 192,
                "podsos2": "189 , 2 , 1"
            },
            "created_at": "01-05-2020 17:38",
            "modified_at": "01-05-2020 17:38",
            "date": "2020-05-19",
            "padej_sup_count": 1,
            "padej_sup_weight": None,
            "padej_podsos_count": None,
            "padej_podsos_weight": None,
            "vinuzhd_sup_count": None,
            "vinuzhd_sup_weight": None,
            "vinuzhd_podsos_count": None,
            "vinuzhd_podsos_weight": None,
            "tr_in_from_1_sup_count": None,
            "tr_in_from_2_sup_count": None,
            "tr_in_podsos_count": None,
            "tr_out_sup_count": None,
            "tr_out_podsos_count": None,
            "count_oporos": 14,
            "count_alive": 173,
            "count_piglets_at_start": 183,
            "tr_out_aka_weight_qnty": None,
            "tr_out_aka_weight_total": None,
            "tr_out_aka_weight_avg": None,
            "piglets_padej_qnty": 7,
            "piglets_vinuzhd_qnty": None,
            "piglets_padej_weight": 0.0,
            "piglets_vinuzhd_weight": None
        },
        {
            "id": 141,
            "count_sows_ws3_start_date": {
                "suporos": 59,
                "suporos2": 59,
                "podsos": 206,
                "podsos2": "203 , 2 , 1"
            },
            "created_at": "01-05-2020 17:38",
            "modified_at": "01-05-2020 17:38",
            "date": "2020-05-20",
            "padej_sup_count": None,
            "padej_sup_weight": None,
            "padej_podsos_count": None,
            "padej_podsos_weight": None,
            "vinuzhd_sup_count": None,
            "vinuzhd_sup_weight": None,
            "vinuzhd_podsos_count": None,
            "vinuzhd_podsos_weight": None,
            "tr_in_from_1_sup_count": None,
            "tr_in_from_2_sup_count": 1,
            "tr_in_podsos_count": None,
            "tr_out_sup_count": None,
            "tr_out_podsos_count": None,
            "count_oporos": 16,
            "count_alive": 178,
            "count_piglets_at_start": 349,
            "tr_out_aka_weight_qnty": None,
            "tr_out_aka_weight_total": None,
            "tr_out_aka_weight_avg": None,
            "piglets_padej_qnty": 11,
            "piglets_vinuzhd_qnty": None,
            "piglets_padej_weight": 0.0,
            "piglets_vinuzhd_weight": None
        },
        {
            "id": 142,
            "count_sows_ws3_start_date": {
                "suporos": 44,
                "suporos2": 44,
                "podsos": 222,
                "podsos2": "218 , 2 , 2"
            },
            "created_at": "01-05-2020 17:38",
            "modified_at": "01-05-2020 17:38",
            "date": "2020-05-21",
            "padej_sup_count": 2,
            "padej_sup_weight": None,
            "padej_podsos_count": 1,
            "padej_podsos_weight": None,
            "vinuzhd_sup_count": None,
            "vinuzhd_sup_weight": None,
            "vinuzhd_podsos_count": None,
            "vinuzhd_podsos_weight": None,
            "tr_in_from_1_sup_count": None,
            "tr_in_from_2_sup_count": None,
            "tr_in_podsos_count": None,
            "tr_out_sup_count": None,
            "tr_out_podsos_count": None,
            "count_oporos": 9,
            "count_alive": 112,
            "count_piglets_at_start": 516,
            "tr_out_aka_weight_qnty": None,
            "tr_out_aka_weight_total": None,
            "tr_out_aka_weight_avg": None,
            "piglets_padej_qnty": 13,
            "piglets_vinuzhd_qnty": None,
            "piglets_padej_weight": 0.0,
            "piglets_vinuzhd_weight": None
        },
        {
            "id": 143,
            "count_sows_ws3_start_date": {
                "suporos": 33,
                "suporos2": 33,
                "podsos": 230,
                "podsos2": "225 , 2 , 3"
            },
            "created_at": "01-05-2020 17:38",
            "modified_at": "01-05-2020 17:38",
            "date": "2020-05-22",
            "padej_sup_count": 1,
            "padej_sup_weight": None,
            "padej_podsos_count": None,
            "padej_podsos_weight": None,
            "vinuzhd_sup_count": None,
            "vinuzhd_sup_weight": None,
            "vinuzhd_podsos_count": None,
            "vinuzhd_podsos_weight": None,
            "tr_in_from_1_sup_count": None,
            "tr_in_from_2_sup_count": None,
            "tr_in_podsos_count": None,
            "tr_out_sup_count": None,
            "tr_out_podsos_count": None,
            "count_oporos": 22,
            "count_alive": 251,
            "count_piglets_at_start": 615,
            "tr_out_aka_weight_qnty": 548,
            "tr_out_aka_weight_total": 4337.0,
            "tr_out_aka_weight_avg": 7.856,
            "piglets_padej_qnty": 9,
            "piglets_vinuzhd_qnty": None,
            "piglets_padej_weight": 0.0,
            "piglets_vinuzhd_weight": None
        },
        {
            "id": 144,
            "count_sows_ws3_start_date": {
                "suporos": 10,
                "suporos2": 10,
                "podsos": 252,
                "podsos2": "246 , 2 , 4"
            },
            "created_at": "01-05-2020 17:38",
            "modified_at": "01-05-2020 17:38",
            "date": "2020-05-23",
            "padej_sup_count": None,
            "padej_sup_weight": None,
            "padej_podsos_count": 1,
            "padej_podsos_weight": None,
            "vinuzhd_sup_count": None,
            "vinuzhd_sup_weight": None,
            "vinuzhd_podsos_count": None,
            "vinuzhd_podsos_weight": None,
            "tr_in_from_1_sup_count": None,
            "tr_in_from_2_sup_count": None,
            "tr_in_podsos_count": None,
            "tr_out_sup_count": None,
            "tr_out_podsos_count": 52,
            "count_oporos": 6,
            "count_alive": 48,
            "count_piglets_at_start": 309,
            "tr_out_aka_weight_qnty": None,
            "tr_out_aka_weight_total": None,
            "tr_out_aka_weight_avg": None,
            "piglets_padej_qnty": 14,
            "piglets_vinuzhd_qnty": None,
            "piglets_padej_weight": 0.0,
            "piglets_vinuzhd_weight": None
        },
        {
            "id": 145,
            "count_sows_ws3_start_date": {
                "suporos": 4,
                "suporos2": 4,
                "podsos": 205,
                "podsos2": "199 , 2 , 4"
            },
            "created_at": "01-05-2020 17:38",
            "modified_at": "01-05-2020 17:38",
            "date": "2020-05-24",
            "padej_sup_count": None,
            "padej_sup_weight": None,
            "padej_podsos_count": None,
            "padej_podsos_weight": None,
            "vinuzhd_sup_count": None,
            "vinuzhd_sup_weight": None,
            "vinuzhd_podsos_count": None,
            "vinuzhd_podsos_weight": None,
            "tr_in_from_1_sup_count": None,
            "tr_in_from_2_sup_count": None,
            "tr_in_podsos_count": None,
            "tr_out_sup_count": None,
            "tr_out_podsos_count": None,
            "count_oporos": 1,
            "count_alive": 5,
            "count_piglets_at_start": 343,
            "tr_out_aka_weight_qnty": None,
            "tr_out_aka_weight_total": None,
            "tr_out_aka_weight_avg": None,
            "piglets_padej_qnty": 8,
            "piglets_vinuzhd_qnty": None,
            "piglets_padej_weight": 0.0,
            "piglets_vinuzhd_weight": None
        },
        {
            "id": 146,
            "count_sows_ws3_start_date": {
                "suporos": 3,
                "suporos2": 3,
                "podsos": 206,
                "podsos2": "200 , 2 , 4"
            },
            "created_at": "01-05-2020 17:38",
            "modified_at": "01-05-2020 17:38",
            "date": "2020-05-25",
            "padej_sup_count": None,
            "padej_sup_weight": None,
            "padej_podsos_count": None,
            "padej_podsos_weight": None,
            "vinuzhd_sup_count": None,
            "vinuzhd_sup_weight": None,
            "vinuzhd_podsos_count": None,
            "vinuzhd_podsos_weight": None,
            "tr_in_from_1_sup_count": None,
            "tr_in_from_2_sup_count": 61,
            "tr_in_podsos_count": None,
            "tr_out_sup_count": None,
            "tr_out_podsos_count": None,
            "count_oporos": 2,
            "count_alive": 21,
            "count_piglets_at_start": 340,
            "tr_out_aka_weight_qnty": None,
            "tr_out_aka_weight_total": None,
            "tr_out_aka_weight_avg": None,
            "piglets_padej_qnty": 13,
            "piglets_vinuzhd_qnty": None,
            "piglets_padej_weight": 0.0,
            "piglets_vinuzhd_weight": None
        },
        {
            "id": 147,
            "count_sows_ws3_start_date": {
                "suporos": 63,
                "suporos2": 63,
                "podsos": 207,
                "podsos2": "201 , 2 , 4"
            },
            "created_at": "01-05-2020 17:38",
            "modified_at": "01-05-2020 17:38",
            "date": "2020-05-26",
            "padej_sup_count": None,
            "padej_sup_weight": None,
            "padej_podsos_count": None,
            "padej_podsos_weight": None,
            "vinuzhd_sup_count": None,
            "vinuzhd_sup_weight": None,
            "vinuzhd_podsos_count": None,
            "vinuzhd_podsos_weight": None,
            "tr_in_from_1_sup_count": None,
            "tr_in_from_2_sup_count": None,
            "tr_in_podsos_count": None,
            "tr_out_sup_count": None,
            "tr_out_podsos_count": None,
            "count_oporos": None,
            "count_alive": None,
            "count_piglets_at_start": 348,
            "tr_out_aka_weight_qnty": None,
            "tr_out_aka_weight_total": None,
            "tr_out_aka_weight_avg": None,
            "piglets_padej_qnty": 13,
            "piglets_vinuzhd_qnty": None,
            "piglets_padej_weight": 0.0,
            "piglets_vinuzhd_weight": None
        },
        {
            "id": 148,
            "count_sows_ws3_start_date": {
                "suporos": 63,
                "suporos2": 63,
                "podsos": 207,
                "podsos2": "201 , 2 , 4"
            },
            "created_at": "01-05-2020 17:38",
            "modified_at": "01-05-2020 17:38",
            "date": "2020-05-27",
            "padej_sup_count": None,
            "padej_sup_weight": None,
            "padej_podsos_count": None,
            "padej_podsos_weight": None,
            "vinuzhd_sup_count": None,
            "vinuzhd_sup_weight": None,
            "vinuzhd_podsos_count": None,
            "vinuzhd_podsos_weight": None,
            "tr_in_from_1_sup_count": None,
            "tr_in_from_2_sup_count": None,
            "tr_in_podsos_count": None,
            "tr_out_sup_count": None,
            "tr_out_podsos_count": None,
            "count_oporos": 5,
            "count_alive": 56,
            "count_piglets_at_start": 335,
            "tr_out_aka_weight_qnty": None,
            "tr_out_aka_weight_total": None,
            "tr_out_aka_weight_avg": None,
            "piglets_padej_qnty": 8,
            "piglets_vinuzhd_qnty": None,
            "piglets_padej_weight": 0.0,
            "piglets_vinuzhd_weight": None
        },
        {
            "id": 149,
            "count_sows_ws3_start_date": {
                "suporos": 59,
                "suporos2": 59,
                "podsos": 212,
                "podsos2": "205 , 2 , 5"
            },
            "created_at": "01-05-2020 17:38",
            "modified_at": "01-05-2020 17:38",
            "date": "2020-05-28",
            "padej_sup_count": None,
            "padej_sup_weight": None,
            "padej_podsos_count": None,
            "padej_podsos_weight": None,
            "vinuzhd_sup_count": None,
            "vinuzhd_sup_weight": None,
            "vinuzhd_podsos_count": None,
            "vinuzhd_podsos_weight": None,
            "tr_in_from_1_sup_count": None,
            "tr_in_from_2_sup_count": None,
            "tr_in_podsos_count": None,
            "tr_out_sup_count": None,
            "tr_out_podsos_count": None,
            "count_oporos": None,
            "count_alive": None,
            "count_piglets_at_start": 383,
            "tr_out_aka_weight_qnty": None,
            "tr_out_aka_weight_total": None,
            "tr_out_aka_weight_avg": None,
            "piglets_padej_qnty": 5,
            "piglets_vinuzhd_qnty": None,
            "piglets_padej_weight": 0.0,
            "piglets_vinuzhd_weight": None
        },
        {
            "id": 150,
            "count_sows_ws3_start_date": {
                "suporos": 59,
                "suporos2": 59,
                "podsos": 212,
                "podsos2": "205 , 2 , 5"
            },
            "created_at": "01-05-2020 17:38",
            "modified_at": "01-05-2020 17:38",
            "date": "2020-05-29",
            "padej_sup_count": None,
            "padej_sup_weight": None,
            "padej_podsos_count": None,
            "padej_podsos_weight": None,
            "vinuzhd_sup_count": None,
            "vinuzhd_sup_weight": None,
            "vinuzhd_podsos_count": None,
            "vinuzhd_podsos_weight": None,
            "tr_in_from_1_sup_count": None,
            "tr_in_from_2_sup_count": None,
            "tr_in_podsos_count": None,
            "tr_out_sup_count": None,
            "tr_out_podsos_count": None,
            "count_oporos": None,
            "count_alive": None,
            "count_piglets_at_start": 378,
            "tr_out_aka_weight_qnty": None,
            "tr_out_aka_weight_total": None,
            "tr_out_aka_weight_avg": None,
            "piglets_padej_qnty": None,
            "piglets_vinuzhd_qnty": None,
            "piglets_padej_weight": None,
            "piglets_vinuzhd_weight": None
        },
        {
            "id": 151,
            "count_sows_ws3_start_date": {
                "suporos": 59,
                "suporos2": 59,
                "podsos": 212,
                "podsos2": "205 , 2 , 5"
            },
            "created_at": "01-05-2020 17:38",
            "modified_at": "01-05-2020 17:38",
            "date": "2020-05-30",
            "padej_sup_count": None,
            "padej_sup_weight": None,
            "padej_podsos_count": None,
            "padej_podsos_weight": None,
            "vinuzhd_sup_count": None,
            "vinuzhd_sup_weight": None,
            "vinuzhd_podsos_count": None,
            "vinuzhd_podsos_weight": None,
            "tr_in_from_1_sup_count": None,
            "tr_in_from_2_sup_count": None,
            "tr_in_podsos_count": None,
            "tr_out_sup_count": None,
            "tr_out_podsos_count": None,
            "count_oporos": None,
            "count_alive": None,
            "count_piglets_at_start": 378,
            "tr_out_aka_weight_qnty": None,
            "tr_out_aka_weight_total": None,
            "tr_out_aka_weight_avg": None,
            "piglets_padej_qnty": None,
            "piglets_vinuzhd_qnty": None,
            "piglets_padej_weight": None,
            "piglets_vinuzhd_weight": None
        }
        ],
        "total_info": {
            "total_tr_in_podsos_count": 1,
            "total_tr_in_from_1_sup_count": None,
            "total_tr_in_from_2_sup_count": 249,
            "total_count_oporos": 230,
            "total_count_alive": 2573,
            "total_tr_out_podsos_count": 222,
            "total_tr_out_sup_count": None,
            "total_padej_podsos_count": 10,
            "total_padej_podsos_weight": None,
            "total_padej_sup_count": 12,
            "total_padej_sup_weight": None,
            "total_vinuzhd_podsos_count": None,
            "total_vinuzhd_podsos_weight": None,
            "total_vinuzhd_sup_count": None,
            "total_vinuzhd_sup_weight": None,
            "total_tr_out_aka_weight_qnty": 2392,
            "total_tr_out_aka_weight_total": 18727.0,
            "avg_tr_out_weight": 7.83591666666667,
            "total_piglets_padej_qnty": 274,
            "total_piglets_padej_weight": 0.0,
            "total_piglets_vinuzhd_qnty": None,
            "total_piglets_vinuzhd_weight": None
        }
    }

    def test_create_semination_lists(self):
        export_to_excel_ws3('../data/ws3header.xlsx', data=self.data)