# -*- coding: utf-8 -*-
from xlrd import open_workbook, xldate_as_tuple
from datetime import timedelta, date, datetime

from django.test import TestCase
from django.utils import timezone
from django.test import tag

from core.utils import export_to_excel_ws3

import locations.testing_utils as locaions_testing
import sows.testing_utils as sows_testings
import sows_events.utils as sows_events_testings
import staff.testing_utils as staff_testings

from sows.models import Sow
from sows_events.models import SowFarrow, CullingSow
from piglets.models import Piglets
from piglets_events.models import CullingPiglets, WeighingPiglets
from transactions.models import SowTransaction, PigletsTransaction
from locations.models import Location
from reports.models import ReportDate
from reports.serializers import ReportDateWs3Serializer


class ExportToExcelTest(TestCase):
    def setUp(self):
        locaions_testing.create_workshops_sections_and_cells()
        sows_testings.create_statuses()
        sows_events_testings.create_types()
        staff_testings.create_svinbin_users()

        self.data_results = [
        {
            "id": 92,
            "count_sows_ws3_start_date": {
                "suporos": 68,
                "suporos2": 68,
                "podsos": 2,
                "podsos2": "2 , 0 , 0"
            },
            "created_at": "01-05-2020 17:38",
            "modified_at": "01-05-2020 17:38",
            "date": "2020-04-01",
            "padej_sup_count": None,
            "padej_sup_weight": None,
            "padej_podsos_count": None,
            "padej_podsos_weight": None,
            "vinuzhd_sup_count": None,
            "vinuzhd_sup_weight": None,
            "vinuzhd_podsos_count": None,
            "vinuzhd_podsos_weight": None,
            "tr_in_from_1_sup_count": None,
            "tr_in_from_2_sup_count": None,
            "tr_in_podsos_count": None,
            "tr_out_sup_count": None,
            "tr_out_podsos_count": 1,
            "count_oporos": 5,
            "count_alive": 51,
            "count_piglets_at_end": 29,
            "tr_out_aka_weight_qnty": 3655,
            "tr_out_aka_weight_total": 23762.0,
            "tr_out_aka_weight_avg": 6.50382352941177,
            "piglets_padej_qnty": None,
            "piglets_vinuzhd_qnty": None,
            "piglets_padej_weight": None,
            "piglets_vinuzhd_weight": None
        },
        {
            "id": 93,
            "count_sows_ws3_start_date": {
                "suporos": 63,
                "suporos2": 63,
                "podsos": 6,
                "podsos2": "6 , 0 , 0"
            },
            "created_at": "01-05-2020 17:38",
            "modified_at": "01-05-2020 17:38",
            "date": "2020-04-02",
            "padej_sup_count": None,
            "padej_sup_weight": None,
            "padej_podsos_count": None,
            "padej_podsos_weight": None,
            "vinuzhd_sup_count": None,
            "vinuzhd_sup_weight": None,
            "vinuzhd_podsos_count": None,
            "vinuzhd_podsos_weight": None,
            "tr_in_from_1_sup_count": None,
            "tr_in_from_2_sup_count": None,
            "tr_in_podsos_count": None,
            "tr_out_sup_count": None,
            "tr_out_podsos_count": None,
            "count_oporos": 12,
            "count_alive": 135,
            "count_piglets_at_end": 80,
            "tr_out_aka_weight_qnty": 110,
            "tr_out_aka_weight_total": 917.0,
            "tr_out_aka_weight_avg": 8.34,
            "piglets_padej_qnty": None,
            "piglets_vinuzhd_qnty": None,
            "piglets_padej_weight": None,
            "piglets_vinuzhd_weight": None
        },
        {
            "id": 94,
            "count_sows_ws3_start_date": {
                "suporos": 51,
                "suporos2": 51,
                "podsos": 18,
                "podsos2": "18 , 0 , 0"
            },
            "created_at": "01-05-2020 17:38",
            "modified_at": "01-05-2020 17:38",
            "date": "2020-04-03",
            "padej_sup_count": None,
            "padej_sup_weight": None,
            "padej_podsos_count": None,
            "padej_podsos_weight": None,
            "vinuzhd_sup_count": None,
            "vinuzhd_sup_weight": None,
            "vinuzhd_podsos_count": None,
            "vinuzhd_podsos_weight": None,
            "tr_in_from_1_sup_count": None,
            "tr_in_from_2_sup_count": None,
            "tr_in_podsos_count": None,
            "tr_out_sup_count": None,
            "tr_out_podsos_count": None,
            "count_oporos": 14,
            "count_alive": 160,
            "count_piglets_at_end": 215,
            "tr_out_aka_weight_qnty": None,
            "tr_out_aka_weight_total": None,
            "tr_out_aka_weight_avg": None,
            "piglets_padej_qnty": None,
            "piglets_vinuzhd_qnty": None,
            "piglets_padej_weight": None,
            "piglets_vinuzhd_weight": None
        },
        {
            "id": 95,
            "count_sows_ws3_start_date": {
                "suporos": 37,
                "suporos2": 37,
                "podsos": 32,
                "podsos2": "32 , 0 , 0"
            },
            "created_at": "01-05-2020 17:38",
            "modified_at": "01-05-2020 17:38",
            "date": "2020-04-04",
            "padej_sup_count": 2,
            "padej_sup_weight": None,
            "padej_podsos_count": 1,
            "padej_podsos_weight": None,
            "vinuzhd_sup_count": None,
            "vinuzhd_sup_weight": None,
            "vinuzhd_podsos_count": None,
            "vinuzhd_podsos_weight": None,
            "tr_in_from_1_sup_count": None,
            "tr_in_from_2_sup_count": None,
            "tr_in_podsos_count": None,
            "tr_out_sup_count": None,
            "tr_out_podsos_count": 1,
            "count_oporos": 13,
            "count_alive": 145,
            "count_piglets_at_end": 375,
            "tr_out_aka_weight_qnty": None,
            "tr_out_aka_weight_total": None,
            "tr_out_aka_weight_avg": None,
            "piglets_padej_qnty": 1,
            "piglets_vinuzhd_qnty": None,
            "piglets_padej_weight": 0.0,
            "piglets_vinuzhd_weight": None
        },
        {
            "id": 96,
            "count_sows_ws3_start_date": {
                "suporos": 21,
                "suporos2": 21,
                "podsos": 43,
                "podsos2": "43 , 0 , 0"
            },
            "created_at": "01-05-2020 17:38",
            "modified_at": "01-05-2020 17:38",
            "date": "2020-04-05",
            "padej_sup_count": 1,
            "padej_sup_weight": None,
            "padej_podsos_count": None,
            "padej_podsos_weight": None,
            "vinuzhd_sup_count": None,
            "vinuzhd_sup_weight": None,
            "vinuzhd_podsos_count": None,
            "vinuzhd_podsos_weight": None,
            "tr_in_from_1_sup_count": None,
            "tr_in_from_2_sup_count": None,
            "tr_in_podsos_count": None,
            "tr_out_sup_count": None,
            "tr_out_podsos_count": None,
            "count_oporos": 5,
            "count_alive": 59,
            "count_piglets_at_end": -13,
            "tr_out_aka_weight_qnty": 537,
            "tr_out_aka_weight_total": 3301.0,
            "tr_out_aka_weight_avg": 6.158,
            "piglets_padej_qnty": 6,
            "piglets_vinuzhd_qnty": None,
            "piglets_padej_weight": 0.0,
            "piglets_vinuzhd_weight": None
        },
        {
            "id": 97,
            "count_sows_ws3_start_date": {
                "suporos": 15,
                "suporos2": 15,
                "podsos": 48,
                "podsos2": "48 , 0 , 0"
            },
            "created_at": "01-05-2020 17:38",
            "modified_at": "01-05-2020 17:38",
            "date": "2020-04-06",
            "padej_sup_count": None,
            "padej_sup_weight": None,
            "padej_podsos_count": None,
            "padej_podsos_weight": None,
            "vinuzhd_sup_count": None,
            "vinuzhd_sup_weight": None,
            "vinuzhd_podsos_count": None,
            "vinuzhd_podsos_weight": None,
            "tr_in_from_1_sup_count": None,
            "tr_in_from_2_sup_count": 69,
            "tr_in_podsos_count": None,
            "tr_out_sup_count": None,
            "tr_out_podsos_count": 1,
            "count_oporos": 2,
            "count_alive": 17,
            "count_piglets_at_end": 40,
            "tr_out_aka_weight_qnty": None,
            "tr_out_aka_weight_total": None,
            "tr_out_aka_weight_avg": None,
            "piglets_padej_qnty": 6,
            "piglets_vinuzhd_qnty": None,
            "piglets_padej_weight": 0.0,
            "piglets_vinuzhd_weight": None
        },
        {
            "id": 98,
            "count_sows_ws3_start_date": {
                "suporos": 77,
                "suporos2": 77,
                "podsos": 50,
                "podsos2": "50 , 0 , 0"
            },
            "created_at": "01-05-2020 17:38",
            "modified_at": "01-05-2020 17:38",
            "date": "2020-04-07",
            "padej_sup_count": 1,
            "padej_sup_weight": None,
            "padej_podsos_count": None,
            "padej_podsos_weight": None,
            "vinuzhd_sup_count": None,
            "vinuzhd_sup_weight": None,
            "vinuzhd_podsos_count": None,
            "vinuzhd_podsos_weight": None,
            "tr_in_from_1_sup_count": None,
            "tr_in_from_2_sup_count": 1,
            "tr_in_podsos_count": None,
            "tr_out_sup_count": None,
            "tr_out_podsos_count": 1,
            "count_oporos": 4,
            "count_alive": 48,
            "count_piglets_at_end": 51,
            "tr_out_aka_weight_qnty": None,
            "tr_out_aka_weight_total": None,
            "tr_out_aka_weight_avg": None,
            "piglets_padej_qnty": 7,
            "piglets_vinuzhd_qnty": None,
            "piglets_padej_weight": 0.0,
            "piglets_vinuzhd_weight": None
        },
        {
            "id": 99,
            "count_sows_ws3_start_date": {
                "suporos": 73,
                "suporos2": 73,
                "podsos": 54,
                "podsos2": "54 , 0 , 0"
            },
            "created_at": "01-05-2020 17:38",
            "modified_at": "01-05-2020 17:38",
            "date": "2020-04-08",
            "padej_sup_count": None,
            "padej_sup_weight": None,
            "padej_podsos_count": 1,
            "padej_podsos_weight": None,
            "vinuzhd_sup_count": None,
            "vinuzhd_sup_weight": None,
            "vinuzhd_podsos_count": None,
            "vinuzhd_podsos_weight": None,
            "tr_in_from_1_sup_count": None,
            "tr_in_from_2_sup_count": None,
            "tr_in_podsos_count": 1,
            "tr_out_sup_count": None,
            "tr_out_podsos_count": 4,
            "count_oporos": 7,
            "count_alive": 60,
            "count_piglets_at_end": 92,
            "tr_out_aka_weight_qnty": None,
            "tr_out_aka_weight_total": None,
            "tr_out_aka_weight_avg": None,
            "piglets_padej_qnty": 4,
            "piglets_vinuzhd_qnty": None,
            "piglets_padej_weight": 0.0,
            "piglets_vinuzhd_weight": None
        },
        {
            "id": 100,
            "count_sows_ws3_start_date": {
                "suporos": 65,
                "suporos2": 65,
                "podsos": 59,
                "podsos2": "59 , 0 , 0"
            },
            "created_at": "01-05-2020 17:38",
            "modified_at": "01-05-2020 17:38",
            "date": "2020-04-09",
            "padej_sup_count": None,
            "padej_sup_weight": None,
            "padej_podsos_count": None,
            "padej_podsos_weight": None,
            "vinuzhd_sup_count": None,
            "vinuzhd_sup_weight": None,
            "vinuzhd_podsos_count": None,
            "vinuzhd_podsos_weight": None,
            "tr_in_from_1_sup_count": None,
            "tr_in_from_2_sup_count": None,
            "tr_in_podsos_count": None,
            "tr_out_sup_count": None,
            "tr_out_podsos_count": 3,
            "count_oporos": 16,
            "count_alive": 174,
            "count_piglets_at_end": 148,
            "tr_out_aka_weight_qnty": None,
            "tr_out_aka_weight_total": None,
            "tr_out_aka_weight_avg": None,
            "piglets_padej_qnty": 7,
            "piglets_vinuzhd_qnty": None,
            "piglets_padej_weight": 0.0,
            "piglets_vinuzhd_weight": None
        },
        {
            "id": 101,
            "count_sows_ws3_start_date": {
                "suporos": 49,
                "suporos2": 49,
                "podsos": 72,
                "podsos2": "72 , 0 , 0"
            },
            "created_at": "01-05-2020 17:38",
            "modified_at": "01-05-2020 17:38",
            "date": "2020-04-10",
            "padej_sup_count": None,
            "padej_sup_weight": None,
            "padej_podsos_count": None,
            "padej_podsos_weight": None,
            "vinuzhd_sup_count": None,
            "vinuzhd_sup_weight": None,
            "vinuzhd_podsos_count": None,
            "vinuzhd_podsos_weight": None,
            "tr_in_from_1_sup_count": None,
            "tr_in_from_2_sup_count": None,
            "tr_in_podsos_count": None,
            "tr_out_sup_count": None,
            "tr_out_podsos_count": 2,
            "count_oporos": 25,
            "count_alive": 269,
            "count_piglets_at_end": 315,
            "tr_out_aka_weight_qnty": None,
            "tr_out_aka_weight_total": None,
            "tr_out_aka_weight_avg": None,
            "piglets_padej_qnty": 7,
            "piglets_vinuzhd_qnty": None,
            "piglets_padej_weight": 0.0,
            "piglets_vinuzhd_weight": None
        },
        {
            "id": 102,
            "count_sows_ws3_start_date": {
                "suporos": 24,
                "suporos2": 24,
                "podsos": 95,
                "podsos2": "95 , 0 , 0"
            },
            "created_at": "01-05-2020 17:38",
            "modified_at": "01-05-2020 17:38",
            "date": "2020-04-11",
            "padej_sup_count": 1,
            "padej_sup_weight": None,
            "padej_podsos_count": 1,
            "padej_podsos_weight": None,
            "vinuzhd_sup_count": None,
            "vinuzhd_sup_weight": None,
            "vinuzhd_podsos_count": None,
            "vinuzhd_podsos_weight": None,
            "tr_in_from_1_sup_count": None,
            "tr_in_from_2_sup_count": None,
            "tr_in_podsos_count": None,
            "tr_out_sup_count": None,
            "tr_out_podsos_count": None,
            "count_oporos": 10,
            "count_alive": 84,
            "count_piglets_at_end": 577,
            "tr_out_aka_weight_qnty": 595,
            "tr_out_aka_weight_total": 4605.0,
            "tr_out_aka_weight_avg": 7.746,
            "piglets_padej_qnty": 2,
            "piglets_vinuzhd_qnty": None,
            "piglets_padej_weight": 0.0,
            "piglets_vinuzhd_weight": None
        },
        {
            "id": 103,
            "count_sows_ws3_start_date": {
                "suporos": 13,
                "suporos2": 13,
                "podsos": 104,
                "podsos2": "104 , 0 , 0"
            },
            "created_at": "01-05-2020 17:38",
            "modified_at": "01-05-2020 17:38",
            "date": "2020-04-12",
            "padej_sup_count": None,
            "padej_sup_weight": None,
            "padej_podsos_count": None,
            "padej_podsos_weight": None,
            "vinuzhd_sup_count": None,
            "vinuzhd_sup_weight": None,
            "vinuzhd_podsos_count": None,
            "vinuzhd_podsos_weight": None,
            "tr_in_from_1_sup_count": None,
            "tr_in_from_2_sup_count": None,
            "tr_in_podsos_count": None,
            "tr_out_sup_count": None,
            "tr_out_podsos_count": None,
            "count_oporos": 3,
            "count_alive": 34,
            "count_piglets_at_end": 65,
            "tr_out_aka_weight_qnty": None,
            "tr_out_aka_weight_total": None,
            "tr_out_aka_weight_avg": None,
            "piglets_padej_qnty": 3,
            "piglets_vinuzhd_qnty": None,
            "piglets_padej_weight": 0.0,
            "piglets_vinuzhd_weight": None
        },
        {
            "id": 104,
            "count_sows_ws3_start_date": {
                "suporos": 10,
                "suporos2": 10,
                "podsos": 107,
                "podsos2": "107 , 0 , 0"
            },
            "created_at": "01-05-2020 17:38",
            "modified_at": "01-05-2020 17:38",
            "date": "2020-04-13",
            "padej_sup_count": None,
            "padej_sup_weight": None,
            "padej_podsos_count": None,
            "padej_podsos_weight": None,
            "vinuzhd_sup_count": None,
            "vinuzhd_sup_weight": None,
            "vinuzhd_podsos_count": None,
            "vinuzhd_podsos_weight": None,
            "tr_in_from_1_sup_count": None,
            "tr_in_from_2_sup_count": 74,
            "tr_in_podsos_count": 3,
            "tr_out_sup_count": None,
            "tr_out_podsos_count": 7,
            "count_oporos": 8,
            "count_alive": 68,
            "count_piglets_at_end": 96,
            "tr_out_aka_weight_qnty": None,
            "tr_out_aka_weight_total": None,
            "tr_out_aka_weight_avg": None,
            "piglets_padej_qnty": 6,
            "piglets_vinuzhd_qnty": None,
            "piglets_padej_weight": 0.0,
            "piglets_vinuzhd_weight": None
        },
        {
            "id": 105,
            "count_sows_ws3_start_date": {
                "suporos": 76,
                "suporos2": 76,
                "podsos": 111,
                "podsos2": "111 , 0 , 0"
            },
            "created_at": "01-05-2020 17:38",
            "modified_at": "01-05-2020 17:38",
            "date": "2020-04-14",
            "padej_sup_count": None,
            "padej_sup_weight": None,
            "padej_podsos_count": None,
            "padej_podsos_weight": None,
            "vinuzhd_sup_count": None,
            "vinuzhd_sup_weight": None,
            "vinuzhd_podsos_count": None,
            "vinuzhd_podsos_weight": None,
            "tr_in_from_1_sup_count": None,
            "tr_in_from_2_sup_count": None,
            "tr_in_podsos_count": None,
            "tr_out_sup_count": None,
            "tr_out_podsos_count": 1,
            "count_oporos": 8,
            "count_alive": 87,
            "count_piglets_at_end": 158,
            "tr_out_aka_weight_qnty": None,
            "tr_out_aka_weight_total": None,
            "tr_out_aka_weight_avg": None,
            "piglets_padej_qnty": 7,
            "piglets_vinuzhd_qnty": None,
            "piglets_padej_weight": 0.0,
            "piglets_vinuzhd_weight": None
        },
        {
            "id": 106,
            "count_sows_ws3_start_date": {
                "suporos": 68,
                "suporos2": 68,
                "podsos": 118,
                "podsos2": "118 , 0 , 0"
            },
            "created_at": "01-05-2020 17:38",
            "modified_at": "01-05-2020 17:38",
            "date": "2020-04-15",
            "padej_sup_count": 1,
            "padej_sup_weight": None,
            "padej_podsos_count": 1,
            "padej_podsos_weight": None,
            "vinuzhd_sup_count": None,
            "vinuzhd_sup_weight": None,
            "vinuzhd_podsos_count": None,
            "vinuzhd_podsos_weight": None,
            "tr_in_from_1_sup_count": None,
            "tr_in_from_2_sup_count": None,
            "tr_in_podsos_count": None,
            "tr_out_sup_count": None,
            "tr_out_podsos_count": 1,
            "count_oporos": 8,
            "count_alive": 101,
            "count_piglets_at_end": 238,
            "tr_out_aka_weight_qnty": None,
            "tr_out_aka_weight_total": None,
            "tr_out_aka_weight_avg": None,
            "piglets_padej_qnty": 3,
            "piglets_vinuzhd_qnty": None,
            "piglets_padej_weight": 0.0,
            "piglets_vinuzhd_weight": None
        },
        {
            "id": 107,
            "count_sows_ws3_start_date": {
                "suporos": 59,
                "suporos2": 59,
                "podsos": 124,
                "podsos2": "124 , 0 , 0"
            },
            "created_at": "01-05-2020 17:38",
            "modified_at": "01-05-2020 17:38",
            "date": "2020-04-16",
            "padej_sup_count": 1,
            "padej_sup_weight": None,
            "padej_podsos_count": None,
            "padej_podsos_weight": None,
            "vinuzhd_sup_count": None,
            "vinuzhd_sup_weight": None,
            "vinuzhd_podsos_count": None,
            "vinuzhd_podsos_weight": None,
            "tr_in_from_1_sup_count": None,
            "tr_in_from_2_sup_count": None,
            "tr_in_podsos_count": None,
            "tr_out_sup_count": None,
            "tr_out_podsos_count": None,
            "count_oporos": 14,
            "count_alive": 179,
            "count_piglets_at_end": 336,
            "tr_out_aka_weight_qnty": None,
            "tr_out_aka_weight_total": None,
            "tr_out_aka_weight_avg": None,
            "piglets_padej_qnty": 4,
            "piglets_vinuzhd_qnty": None,
            "piglets_padej_weight": 0.0,
            "piglets_vinuzhd_weight": None
        },
        {
            "id": 108,
            "count_sows_ws3_start_date": {
                "suporos": 44,
                "suporos2": 44,
                "podsos": 138,
                "podsos2": "138 , 0 , 0"
            },
            "created_at": "01-05-2020 17:38",
            "modified_at": "01-05-2020 17:38",
            "date": "2020-04-17",
            "padej_sup_count": None,
            "padej_sup_weight": None,
            "padej_podsos_count": 1,
            "padej_podsos_weight": None,
            "vinuzhd_sup_count": None,
            "vinuzhd_sup_weight": None,
            "vinuzhd_podsos_count": None,
            "vinuzhd_podsos_weight": None,
            "tr_in_from_1_sup_count": None,
            "tr_in_from_2_sup_count": None,
            "tr_in_podsos_count": None,
            "tr_out_sup_count": None,
            "tr_out_podsos_count": 2,
            "count_oporos": 15,
            "count_alive": 175,
            "count_piglets_at_end": 511,
            "tr_out_aka_weight_qnty": None,
            "tr_out_aka_weight_total": None,
            "tr_out_aka_weight_avg": None,
            "piglets_padej_qnty": 7,
            "piglets_vinuzhd_qnty": None,
            "piglets_padej_weight": 0.0,
            "piglets_vinuzhd_weight": None
        },
        {
            "id": 109,
            "count_sows_ws3_start_date": {
                "suporos": 29,
                "suporos2": 29,
                "podsos": 150,
                "podsos2": "150 , 0 , 0"
            },
            "created_at": "01-05-2020 17:38",
            "modified_at": "01-05-2020 17:38",
            "date": "2020-04-18",
            "padej_sup_count": None,
            "padej_sup_weight": None,
            "padej_podsos_count": None,
            "padej_podsos_weight": None,
            "vinuzhd_sup_count": None,
            "vinuzhd_sup_weight": None,
            "vinuzhd_podsos_count": None,
            "vinuzhd_podsos_weight": None,
            "tr_in_from_1_sup_count": None,
            "tr_in_from_2_sup_count": None,
            "tr_in_podsos_count": None,
            "tr_out_sup_count": None,
            "tr_out_podsos_count": 4,
            "count_oporos": 12,
            "count_alive": 120,
            "count_piglets_at_end": 679,
            "tr_out_aka_weight_qnty": 621,
            "tr_out_aka_weight_total": 4993.0,
            "tr_out_aka_weight_avg": 8.005,
            "piglets_padej_qnty": None,
            "piglets_vinuzhd_qnty": None,
            "piglets_padej_weight": None,
            "piglets_vinuzhd_weight": None
        },
        {
            "id": 110,
            "count_sows_ws3_start_date": {
                "suporos": 17,
                "suporos2": 17,
                "podsos": 158,
                "podsos2": "158 , 0 , 0"
            },
            "created_at": "01-05-2020 17:38",
            "modified_at": "01-05-2020 17:38",
            "date": "2020-04-19",
            "padej_sup_count": None,
            "padej_sup_weight": None,
            "padej_podsos_count": None,
            "padej_podsos_weight": None,
            "vinuzhd_sup_count": None,
            "vinuzhd_sup_weight": None,
            "vinuzhd_podsos_count": None,
            "vinuzhd_podsos_weight": None,
            "tr_in_from_1_sup_count": None,
            "tr_in_from_2_sup_count": None,
            "tr_in_podsos_count": None,
            "tr_out_sup_count": None,
            "tr_out_podsos_count": None,
            "count_oporos": 9,
            "count_alive": 87,
            "count_piglets_at_end": 178,
            "tr_out_aka_weight_qnty": None,
            "tr_out_aka_weight_total": None,
            "tr_out_aka_weight_avg": None,
            "piglets_padej_qnty": 10,
            "piglets_vinuzhd_qnty": None,
            "piglets_padej_weight": 0.0,
            "piglets_vinuzhd_weight": None
        },
        {
            "id": 111,
            "count_sows_ws3_start_date": {
                "suporos": 8,
                "suporos2": 8,
                "podsos": 167,
                "podsos2": "167 , 0 , 0"
            },
            "created_at": "01-05-2020 17:38",
            "modified_at": "01-05-2020 17:38",
            "date": "2020-04-20",
            "padej_sup_count": None,
            "padej_sup_weight": None,
            "padej_podsos_count": 3,
            "padej_podsos_weight": None,
            "vinuzhd_sup_count": None,
            "vinuzhd_sup_weight": None,
            "vinuzhd_podsos_count": None,
            "vinuzhd_podsos_weight": None,
            "tr_in_from_1_sup_count": None,
            "tr_in_from_2_sup_count": None,
            "tr_in_podsos_count": None,
            "tr_out_sup_count": None,
            "tr_out_podsos_count": None,
            "count_oporos": 4,
            "count_alive": 37,
            "count_piglets_at_end": 255,
            "tr_out_aka_weight_qnty": None,
            "tr_out_aka_weight_total": None,
            "tr_out_aka_weight_avg": None,
            "piglets_padej_qnty": 10,
            "piglets_vinuzhd_qnty": None,
            "piglets_padej_weight": 0.0,
            "piglets_vinuzhd_weight": None
        },
        {
            "id": 112,
            "count_sows_ws3_start_date": {
                "suporos": 4,
                "suporos2": 4,
                "podsos": 168,
                "podsos2": "168 , 0 , 0"
            },
            "created_at": "01-05-2020 17:38",
            "modified_at": "01-05-2020 17:38",
            "date": "2020-04-21",
            "padej_sup_count": None,
            "padej_sup_weight": None,
            "padej_podsos_count": None,
            "padej_podsos_weight": None,
            "vinuzhd_sup_count": None,
            "vinuzhd_sup_weight": None,
            "vinuzhd_podsos_count": None,
            "vinuzhd_podsos_weight": None,
            "tr_in_from_1_sup_count": None,
            "tr_in_from_2_sup_count": None,
            "tr_in_podsos_count": None,
            "tr_out_sup_count": None,
            "tr_out_podsos_count": None,
            "count_oporos": 1,
            "count_alive": 8,
            "count_piglets_at_end": 282,
            "tr_out_aka_weight_qnty": None,
            "tr_out_aka_weight_total": None,
            "tr_out_aka_weight_avg": None,
            "piglets_padej_qnty": 5,
            "piglets_vinuzhd_qnty": None,
            "piglets_padej_weight": 0.0,
            "piglets_vinuzhd_weight": None
        },
        {
            "id": 113,
            "count_sows_ws3_start_date": {
                "suporos": 3,
                "suporos2": 3,
                "podsos": 169,
                "podsos2": "169 , 0 , 0"
            },
            "created_at": "01-05-2020 17:38",
            "modified_at": "01-05-2020 17:38",
            "date": "2020-04-22",
            "padej_sup_count": None,
            "padej_sup_weight": None,
            "padej_podsos_count": None,
            "padej_podsos_weight": None,
            "vinuzhd_sup_count": None,
            "vinuzhd_sup_weight": None,
            "vinuzhd_podsos_count": None,
            "vinuzhd_podsos_weight": None,
            "tr_in_from_1_sup_count": None,
            "tr_in_from_2_sup_count": None,
            "tr_in_podsos_count": None,
            "tr_out_sup_count": None,
            "tr_out_podsos_count": None,
            "count_oporos": None,
            "count_alive": None,
            "count_piglets_at_end": 285,
            "tr_out_aka_weight_qnty": 574,
            "tr_out_aka_weight_total": 4008.0,
            "tr_out_aka_weight_avg": 7.0,
            "piglets_padej_qnty": 9,
            "piglets_vinuzhd_qnty": None,
            "piglets_padej_weight": 0.0,
            "piglets_vinuzhd_weight": None
        },
        {
            "id": 114,
            "count_sows_ws3_start_date": {
                "suporos": 3,
                "suporos2": 3,
                "podsos": 169,
                "podsos2": "169 , 0 , 0"
            },
            "created_at": "01-05-2020 17:38",
            "modified_at": "01-05-2020 17:38",
            "date": "2020-04-23",
            "padej_sup_count": None,
            "padej_sup_weight": None,
            "padej_podsos_count": None,
            "padej_podsos_weight": None,
            "vinuzhd_sup_count": None,
            "vinuzhd_sup_weight": None,
            "vinuzhd_podsos_count": None,
            "vinuzhd_podsos_weight": None,
            "tr_in_from_1_sup_count": None,
            "tr_in_from_2_sup_count": None,
            "tr_in_podsos_count": None,
            "tr_out_sup_count": None,
            "tr_out_podsos_count": None,
            "count_oporos": None,
            "count_alive": None,
            "count_piglets_at_end": 276,
            "tr_out_aka_weight_qnty": None,
            "tr_out_aka_weight_total": None,
            "tr_out_aka_weight_avg": None,
            "piglets_padej_qnty": 10,
            "piglets_vinuzhd_qnty": None,
            "piglets_padej_weight": 0.0,
            "piglets_vinuzhd_weight": None
        },
        {
            "id": 115,
            "count_sows_ws3_start_date": {
                "suporos": 3,
                "suporos2": 3,
                "podsos": 169,
                "podsos2": "169 , 0 , 0"
            },
            "created_at": "01-05-2020 17:38",
            "modified_at": "01-05-2020 17:38",
            "date": "2020-04-24",
            "padej_sup_count": None,
            "padej_sup_weight": None,
            "padej_podsos_count": None,
            "padej_podsos_weight": None,
            "vinuzhd_sup_count": None,
            "vinuzhd_sup_weight": None,
            "vinuzhd_podsos_count": None,
            "vinuzhd_podsos_weight": None,
            "tr_in_from_1_sup_count": None,
            "tr_in_from_2_sup_count": None,
            "tr_in_podsos_count": None,
            "tr_out_sup_count": None,
            "tr_out_podsos_count": None,
            "count_oporos": None,
            "count_alive": None,
            "count_piglets_at_end": 266,
            "tr_out_aka_weight_qnty": None,
            "tr_out_aka_weight_total": None,
            "tr_out_aka_weight_avg": None,
            "piglets_padej_qnty": 6,
            "piglets_vinuzhd_qnty": None,
            "piglets_padej_weight": 0.0,
            "piglets_vinuzhd_weight": None
        },
        {
            "id": 116,
            "count_sows_ws3_start_date": {
                "suporos": 3,
                "suporos2": 3,
                "podsos": 169,
                "podsos2": "169 , 0 , 0"
            },
            "created_at": "01-05-2020 17:38",
            "modified_at": "01-05-2020 17:38",
            "date": "2020-04-25",
            "padej_sup_count": None,
            "padej_sup_weight": None,
            "padej_podsos_count": None,
            "padej_podsos_weight": None,
            "vinuzhd_sup_count": None,
            "vinuzhd_sup_weight": None,
            "vinuzhd_podsos_count": None,
            "vinuzhd_podsos_weight": None,
            "tr_in_from_1_sup_count": None,
            "tr_in_from_2_sup_count": 63,
            "tr_in_podsos_count": None,
            "tr_out_sup_count": None,
            "tr_out_podsos_count": 33,
            "count_oporos": None,
            "count_alive": None,
            "count_piglets_at_end": 260,
            "tr_out_aka_weight_qnty": None,
            "tr_out_aka_weight_total": None,
            "tr_out_aka_weight_avg": None,
            "piglets_padej_qnty": 5,
            "piglets_vinuzhd_qnty": None,
            "piglets_padej_weight": 0.0,
            "piglets_vinuzhd_weight": None
        },
        {
            "id": 117,
            "count_sows_ws3_start_date": {
                "suporos": 0,
                "suporos2": 0,
                "podsos": 139,
                "podsos2": "139 , 0 , 0"
            },
            "created_at": "01-05-2020 17:38",
            "modified_at": "01-05-2020 17:38",
            "date": "2020-04-26",
            "padej_sup_count": None,
            "padej_sup_weight": None,
            "padej_podsos_count": None,
            "padej_podsos_weight": None,
            "vinuzhd_sup_count": None,
            "vinuzhd_sup_weight": None,
            "vinuzhd_podsos_count": None,
            "vinuzhd_podsos_weight": None,
            "tr_in_from_1_sup_count": None,
            "tr_in_from_2_sup_count": 1,
            "tr_in_podsos_count": None,
            "tr_out_sup_count": None,
            "tr_out_podsos_count": None,
            "count_oporos": 1,
            "count_alive": 16,
            "count_piglets_at_end": -319,
            "tr_out_aka_weight_qnty": None,
            "tr_out_aka_weight_total": None,
            "tr_out_aka_weight_avg": None,
            "piglets_padej_qnty": 2,
            "piglets_vinuzhd_qnty": None,
            "piglets_padej_weight": 0.0,
            "piglets_vinuzhd_weight": None
        },
        {
            "id": 118,
            "count_sows_ws3_start_date": {
                "suporos": 0,
                "suporos2": 0,
                "podsos": 140,
                "podsos2": "140 , 0 , 0"
            },
            "created_at": "01-05-2020 17:38",
            "modified_at": "01-05-2020 17:38",
            "date": "2020-04-27",
            "padej_sup_count": None,
            "padej_sup_weight": None,
            "padej_podsos_count": 2,
            "padej_podsos_weight": None,
            "vinuzhd_sup_count": None,
            "vinuzhd_sup_weight": None,
            "vinuzhd_podsos_count": None,
            "vinuzhd_podsos_weight": None,
            "tr_in_from_1_sup_count": None,
            "tr_in_from_2_sup_count": 66,
            "tr_in_podsos_count": None,
            "tr_out_sup_count": None,
            "tr_out_podsos_count": 2,
            "count_oporos": 49,
            "count_alive": 533,
            "count_piglets_at_end": -305,
            "tr_out_aka_weight_qnty": None,
            "tr_out_aka_weight_total": None,
            "tr_out_aka_weight_avg": None,
            "piglets_padej_qnty": 10,
            "piglets_vinuzhd_qnty": None,
            "piglets_padej_weight": 0.0,
            "piglets_vinuzhd_weight": None
        },
        {
            "id": 119,
            "count_sows_ws3_start_date": {
                "suporos": 65,
                "suporos2": 65,
                "podsos": 185,
                "podsos2": "185 , 0 , 0"
            },
            "created_at": "01-05-2020 17:38",
            "modified_at": "01-05-2020 17:38",
            "date": "2020-04-28",
            "padej_sup_count": None,
            "padej_sup_weight": None,
            "padej_podsos_count": None,
            "padej_podsos_weight": None,
            "vinuzhd_sup_count": None,
            "vinuzhd_sup_weight": None,
            "vinuzhd_podsos_count": None,
            "vinuzhd_podsos_weight": None,
            "tr_in_from_1_sup_count": None,
            "tr_in_from_2_sup_count": None,
            "tr_in_podsos_count": None,
            "tr_out_sup_count": None,
            "tr_out_podsos_count": None,
            "count_oporos": 4,
            "count_alive": 42,
            "count_piglets_at_end": 218,
            "tr_out_aka_weight_qnty": None,
            "tr_out_aka_weight_total": None,
            "tr_out_aka_weight_avg": None,
            "piglets_padej_qnty": 5,
            "piglets_vinuzhd_qnty": None,
            "piglets_padej_weight": 0.0,
            "piglets_vinuzhd_weight": None
        },
        {
            "id": 120,
            "count_sows_ws3_start_date": {
                "suporos": 64,
                "suporos2": 64,
                "podsos": 189,
                "podsos2": "189 , 0 , 0"
            },
            "created_at": "01-05-2020 17:38",
            "modified_at": "01-05-2020 17:38",
            "date": "2020-04-29",
            "padej_sup_count": None,
            "padej_sup_weight": None,
            "padej_podsos_count": None,
            "padej_podsos_weight": None,
            "vinuzhd_sup_count": None,
            "vinuzhd_sup_weight": None,
            "vinuzhd_podsos_count": None,
            "vinuzhd_podsos_weight": None,
            "tr_in_from_1_sup_count": None,
            "tr_in_from_2_sup_count": None,
            "tr_in_podsos_count": None,
            "tr_out_sup_count": None,
            "tr_out_podsos_count": None,
            "count_oporos": 10,
            "count_alive": 119,
            "count_piglets_at_end": 255,
            "tr_out_aka_weight_qnty": None,
            "tr_out_aka_weight_total": None,
            "tr_out_aka_weight_avg": None,
            "piglets_padej_qnty": 15,
            "piglets_vinuzhd_qnty": None,
            "piglets_padej_weight": 0.0,
            "piglets_vinuzhd_weight": None
        },
        {
            "id": 121,
            "count_sows_ws3_start_date": {
                "suporos": 62,
                "suporos2": 62,
                "podsos": 199,
                "podsos2": "199 , 0 , 0"
            },
            "created_at": "01-05-2020 17:38",
            "modified_at": "01-05-2020 17:38",
            "date": "2020-04-30",
            "padej_sup_count": 1,
            "padej_sup_weight": None,
            "padej_podsos_count": 3,
            "padej_podsos_weight": None,
            "vinuzhd_sup_count": None,
            "vinuzhd_sup_weight": None,
            "vinuzhd_podsos_count": None,
            "vinuzhd_podsos_weight": None,
            "tr_in_from_1_sup_count": None,
            "tr_in_from_2_sup_count": None,
            "tr_in_podsos_count": None,
            "tr_out_sup_count": None,
            "tr_out_podsos_count": None,
            "count_oporos": 10,
            "count_alive": 119,
            "count_piglets_at_end": 359,
            "tr_out_aka_weight_qnty": None,
            "tr_out_aka_weight_total": None,
            "tr_out_aka_weight_avg": None,
            "piglets_padej_qnty": 7,
            "piglets_vinuzhd_qnty": None,
            "piglets_padej_weight": 0.0,
            "piglets_vinuzhd_weight": None
        }
    ]

    def test_create_semination_lists(self):
        export_to_excel_ws3('TestWs3.xlsx', data=self.data)